import Link from "next/link";
import { resolveQualityIssue } from "@/app/buying-actions";
import { PageHeader, StatusIndicator } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/pricing";
import { statusLabel } from "@/lib/presentation/status";
import { resolveScope } from "@/lib/scope";

export default async function Problemi() {
  const context = await requireRoles(["RSA_DIRECTOR", "AREA_MANAGER", "PROCUREMENT_MANAGER"]);
  const scope = await resolveScope(context.assignment);
  const issues = await prisma.qualityIssue.findMany({ where: context.roleCode === "PROCUREMENT_MANAGER" ? {} : { purchaseOrderLine: { purchaseOrder: { facilityId: { in: scope.facilityIds } } } }, include: { purchaseOrderLine: { include: { purchaseOrder: { include: { supplier: true, facility: true } }, canonicalProduct: true } } }, orderBy: { openedAt: "desc" } });
  return <main><PageHeader eyebrow="Qualità fornitura" title="Non conformità" description="Dalla segnalazione alla risoluzione, con responsabilità e storico chiari." /><div className="issue-summary"><div><strong>{issues.filter(({ status }) => status === "OPEN").length}</strong><span>Aperte</span></div><div><strong>{issues.filter(({ status }) => status === "UNDER_REVIEW").length}</strong><span>In valutazione</span></div><div><strong>{issues.filter(({ severity }) => severity === "HIGH" || severity === "CRITICAL").length}</strong><span>Ad alta priorità</span></div><div><strong>{issues.filter(({ status }) => status === "RESOLVED" || status === "CLOSED").length}</strong><span>Risolte</span></div></div><div className="issue-list">{issues.map((issue) => { const order = issue.purchaseOrderLine.purchaseOrder; return <article key={issue.id}><div className={`severity severity-${issue.severity.toLowerCase()}`}>{statusLabel(issue.severity)}</div><div><span>{statusLabel(issue.issueType)} · {order.facility.name}</span><h2>{issue.purchaseOrderLine.canonicalProduct.name}</h2><p>{issue.description}</p><small><Link href={`/orders/${order.id}`}>{order.poNumber}</Link> · {order.supplier.name} · {formatDate(issue.openedAt)} · {Number(issue.affectedQuantity)} unità</small></div><StatusIndicator active={issue.status === "RESOLVED" || issue.status === "CLOSED"} label={statusLabel(issue.status)} />{context.roleCode === "PROCUREMENT_MANAGER" && !["RESOLVED", "CLOSED"].includes(issue.status) && <form action={resolveQualityIssue}><input type="hidden" name="issueId" value={issue.id} /><select name="status"><option value="UNDER_REVIEW">Prendi in carico</option><option value="RESOLVED">Risolvi</option><option value="CLOSED">Chiudi</option></select><select name="resolutionType"><option value="replacement">Sostituzione</option><option value="credit">Nota di credito attesa</option><option value="accepted">Accettato</option><option value="rejected">Contestato</option></select><input name="note" placeholder="Nota di risoluzione" /><button>Salva</button></form>}</article>; })}</div></main>;
}
