import Link from "next/link";
import { Prisma } from "@prisma/client";
import { resolveQualityIssue } from "@/app/buying-actions";
import { EmptyState, PageHeader, Pagination, StatusChip } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/pricing";
import { statusLabel } from "@/lib/presentation/status";
import { resolveScope } from "@/lib/scope";

const PAGE_SIZE = 20;

export default async function Problemi({ searchParams }: { searchParams: Promise<{ stato?: string; severita?: string; pagina?: string }> }) {
  const context = await requireRoles(["RSA_DIRECTOR", "AREA_MANAGER", "PROCUREMENT_MANAGER"]), scope = await resolveScope(context.assignment), query = await searchParams, page = Math.max(1, Number(query.pagina ?? 1));
  const where: Prisma.QualityIssueWhereInput = { purchaseOrderLine: { purchaseOrder: { organizationId: context.organization.id, ...(context.roleCode === "PROCUREMENT_MANAGER" ? {} : { facilityId: { in: scope.facilityIds } }) } }, ...(query.stato ? { status: query.stato as never } : {}), ...(query.severita ? { severity: query.severita as never } : {}) };
  const [total, issues, open, review, critical, resolved] = await Promise.all([
    prisma.qualityIssue.count({ where }), prisma.qualityIssue.findMany({ where, include: { attachments: true, purchaseOrderLine: { include: { purchaseOrder: { include: { supplier: true, facility: true } }, canonicalProduct: true } } }, orderBy: [{ severity: "desc" }, { openedAt: "asc" }], skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE }),
    prisma.qualityIssue.count({ where: { ...where, status: "OPEN" } }), prisma.qualityIssue.count({ where: { ...where, status: "UNDER_REVIEW" } }), prisma.qualityIssue.count({ where: { ...where, severity: { in: ["HIGH", "CRITICAL"] }, status: { notIn: ["RESOLVED", "CLOSED"] } } }), prisma.qualityIssue.count({ where: { ...where, status: { in: ["RESOLVED", "CLOSED"] } } }),
  ]);
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  return <main className="phase2-page phase2-issues"><PageHeader eyebrow="Qualità fornitura" title="Non conformità" description={`${total} casi nel filtro · evidenze e risoluzioni tracciate`} />
    <section className="phase2-summary-strip"><div><span>Aperte</span><strong>{open}</strong><small>Da assegnare o valutare</small></div><div><span>In valutazione</span><strong>{review}</strong><small>Con owner operativo</small></div><div><span>Alta priorità</span><strong>{critical}</strong><small>Aperte o in valutazione</small></div><div><span>Risolte</span><strong>{resolved}</strong><small>Nel filtro corrente</small></div></section>
    <form className="phase2-control-bar"><select name="stato" defaultValue={query.stato ?? ""}><option value="">Tutti gli stati</option><option value="OPEN">Aperte</option><option value="UNDER_REVIEW">In valutazione</option><option value="RESOLVED">Risolte</option><option value="CLOSED">Chiuse</option></select><select name="severita" defaultValue={query.severita ?? ""}><option value="">Tutte le gravità</option><option value="CRITICAL">Critica</option><option value="HIGH">Alta</option><option value="MEDIUM">Media</option><option value="LOW">Bassa</option></select><button className="secondary-cta">Filtra</button></form>
    {issues.length ? <section className="phase2-issue-list">{issues.map((issue) => { const order = issue.purchaseOrderLine.purchaseOrder, closed = ["RESOLVED", "CLOSED"].includes(issue.status); return <article key={issue.id}><header><div><span>{statusLabel(issue.issueType)} · {order.facility.name}</span><h2>{issue.purchaseOrderLine.canonicalProduct.name}</h2><p>{issue.description}</p></div><StatusChip variant={closed ? "ok" : issue.severity === "CRITICAL" ? "danger" : "warn"}>{statusLabel(issue.severity)} · {statusLabel(issue.status)}</StatusChip></header><div className="phase2-issue-meta"><Link href={`/orders/${order.id}`}>{order.poNumber}</Link><span>{order.supplier.name}</span><span>Aperta {formatDate(issue.openedAt)}</span><span>{Number(issue.affectedQuantity)} unità</span></div>{issue.attachments.length > 0 && <div className="phase2-attachments">{issue.attachments.map((attachment) => <Link key={attachment.id} href={`/attachments/${attachment.id}`}>{attachment.originalFilename}</Link>)}</div>}{context.roleCode === "PROCUREMENT_MANAGER" && !closed && <details className="phase2-resolution"><summary>Prendi in carico o risolvi</summary><form action={resolveQualityIssue}><input type="hidden" name="issueId" value={issue.id} /><select name="status"><option value="UNDER_REVIEW">Prendi in carico</option><option value="RESOLVED">Risolvi</option><option value="CLOSED">Chiudi</option></select><select name="resolutionType"><option value="replacement">Sostituzione</option><option value="credit">Nota di credito attesa</option><option value="accepted">Accettato</option><option value="rejected">Contestato</option></select><input name="note" placeholder="Nota di risoluzione" /><input name="attachments" type="file" multiple accept="image/png,image/jpeg,application/pdf" /><button className="primary-cta">Salva decisione</button></form></details>}</article>; })}<Pagination page={Math.min(page, pages)} pages={pages} pathname="/non-conformita" params={{ stato: query.stato, severita: query.severita }} /></section> : <EmptyState title="Nessuna non conformità" description="Le difformità registrate in ricezione compariranno qui con evidenze e stato." />}
  </main>;
}
