import { DataTable, PageHeader, ScopeBadge, StatusIndicator } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { formatMoney } from "@/lib/pricing";
import { prisma } from "@/lib/prisma";

async function scopeNames(assignments: { scopeType: string; scopeId: string | null }[]) { const ids = assignments.map((a) => a.scopeId).filter(Boolean) as string[]; const [areas, facilities] = await Promise.all([prisma.area.findMany({ where: { id: { in: ids } } }), prisma.facility.findMany({ where: { id: { in: ids } } })]); return new Map([...areas, ...facilities].map((item) => [item.id, item.name])); }
export default async function UsersPage() {
  const context = await requireRoles(["PROCUREMENT_ADMIN"]); const assignments = await prisma.userAssignment.findMany({ where: { organizationId: context.organization.id }, include: { user: true, role: true, organization: true }, orderBy: { user: { name: "asc" } } }); const names = await scopeNames(assignments);
  return <main><PageHeader eyebrow="Identity & authority" title="Users" description="Role defines capability. Scope defines where that capability applies." /><aside className="principle-note"><b>Role ≠ scope</b><span>Each assignment combines a user, capability role, organization boundary, operational scope and authority.</span></aside><DataTable label="User assignments"><thead><tr><th>User</th><th>Role</th><th>Organization</th><th>Scope</th><th>Approval limit</th><th>Status</th></tr></thead><tbody>{assignments.map((assignment) => <tr key={assignment.id}><td><strong>{assignment.user.name}</strong><small className="cell-detail">{assignment.user.email}</small></td><td>{assignment.role.name}</td><td>{assignment.organization.name}</td><td><ScopeBadge type={assignment.scopeType} label={assignment.scopeType === "ORGANIZATION" ? assignment.organization.name : names.get(assignment.scopeId ?? "") ?? "Unknown scope"} /></td><td>{assignment.approvalLimit ? formatMoney(Number(assignment.approvalLimit)) : "—"}</td><td><StatusIndicator active={assignment.active} /></td></tr>)}</tbody></DataTable></main>;
}
