import Link from "next/link";
import { notFound } from "next/navigation";
import { DataTable, PageHeader, StatusIndicator } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { formatDate, formatMoney, getComparablePrice } from "@/lib/pricing";
import { prisma } from "@/lib/prisma";

export default async function SupplierDetail({ params }: { params: Promise<{ id: string }> }) {
  await requireRoles(["PROCUREMENT_MANAGER", "PROCUREMENT_ADMIN"]); const { id } = await params; const supplier = await prisma.supplier.findUnique({ where: { id }, include: { priceLists: { include: { _count: { select: { offers: true } } } }, offers: { include: { canonicalProduct: true } } } }); if (!supplier) notFound();
  return <main><PageHeader eyebrow="Supplier profile" title={supplier.name} description={supplier.vatNumber ? `VAT ${supplier.vatNumber}` : "VAT not available"} /><section className="definition-grid"><div><span>Status</span><StatusIndicator active={supplier.active} /></div><div><span>Price lists</span><strong>{supplier.priceLists.length}</strong></div><div><span>Offered products</span><strong>{supplier.offers.length}</strong></div><div><span>Preferred offers</span><strong>{supplier.offers.filter((o) => o.preferred).length}</strong></div></section><section className="section-heading"><div><p className="eyebrow">Commercial coverage</p><h2>Price lists</h2></div></section><DataTable label="Supplier price lists"><thead><tr><th>List</th><th>Validity</th><th>Status</th><th>Items</th></tr></thead><tbody>{supplier.priceLists.map((list) => <tr key={list.id}><td>{list.name}</td><td>{formatDate(list.validFrom)} – {formatDate(list.validUntil)}</td><td><StatusIndicator active={list.active} /></td><td>{list._count.offers}</td></tr>)}</tbody></DataTable><section className="section-heading"><div><p className="eyebrow">Catalog</p><h2>Offered products</h2></div></section><DataTable label="Offered products"><thead><tr><th>Product</th><th>Supplier SKU</th><th>Price</th><th>Normalized</th><th>Status</th></tr></thead><tbody>{supplier.offers.map((offer) => <tr key={offer.id}><td><Link className="table-link" href={`/products/${offer.canonicalProduct.id}`}>{offer.canonicalProduct.name}</Link></td><td className="mono">{offer.supplierSku ?? "—"}</td><td>{formatMoney(Number(offer.unitPrice))}</td><td>{formatMoney(getComparablePrice(offer), 4)}</td><td>{offer.preferred ? "Preferred" : "Available"}</td></tr>)}</tbody></DataTable></main>;
}
