import Link from "next/link";
import { notFound } from "next/navigation";
import { acceptRecord, confirmNewProduct, correctAndAcceptRecord, markRecord } from "../../../actions";
import { Confidence, ImportStatus, SourceReference } from "@/components/import-primitives";
import { DataTable, PageHeader } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { consumptionUomLabel, fieldLabels, interpretationProviderLabel, matchTypeLabels, purchaseUomLabel } from "@/lib/imports/presentation";
import type { ImportField, NormalizedImport, SourceLocator } from "@/lib/imports/types";
import { prisma } from "@/lib/prisma";
import { formatDate, formatMoney } from "@/lib/pricing";

function displayValue(value: unknown) { return value === null || value === undefined ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value); }
function readableField(key: string) { return fieldLabels[key as ImportField] ?? key; }
function presentFieldValue(key: string, value: unknown) { return key === "purchaseUom" ? purchaseUomLabel(value) : key === "consumptionUom" ? consumptionUomLabel(value) : displayValue(value); }
function list(value: unknown) { return Array.isArray(value) ? value.map(String) : []; }
const exceptionLabels: Record<string, string> = { UNCERTAIN_MATCH: "Match incerto", UOM_AMBIGUOUS: "Unità ambigua", PACKAGE_AMBIGUOUS: "Confezione ambigua", PRICE_NOT_NORMALIZABLE: "Prezzo non normalizzabile", IDENTIFIER_CONFLICT: "Identificatore in conflitto", NEW_PRODUCT: "Nuovo prodotto", PACKAGE_CHANGE: "Cambio confezione", CATEGORY_UNCERTAIN: "Categoria incerta", MISSING_DATA: "Dato mancante" };
function candidateDifference(label: string, source: unknown, target: unknown) { const equal = String(source ?? "").toLocaleLowerCase("it-IT") === String(target ?? "").toLocaleLowerCase("it-IT"); return <div className={equal ? "same" : "different"}><span>{label}</span><strong>{displayValue(source)}</strong><i aria-hidden="true">→</i><strong>{displayValue(target)}</strong></div>; }

export default async function RecordReviewPage({ params, searchParams }: { params: Promise<{ id: string; recordId: string }>; searchParams: Promise<{ corretto?: string }> }) {
  const context = await requireRoles(["PROCUREMENT_MANAGER", "PROCUREMENT_ADMIN"]);
  const { id, recordId } = await params;
  const record = await prisma.importedRecord.findFirst({ where: { id: recordId, importJobId: id, importJob: { sourceDocument: { organizationId: context.assignment.organizationId } } }, include: { importJob: { include: { sourceDocument: { include: { supplier: true } } } }, matchCandidates: { include: { canonicalProduct: { include: { category: true } } }, orderBy: [{ recommended: "desc" }, { score: "desc" }] }, corrections: { include: { correctedBy: true }, orderBy: { correctedAt: "desc" } }, fieldValues: { include: { confirmedBy: true }, orderBy: { fieldName: "asc" } } } });
  if (!record) notFound();
  const categories = await prisma.category.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true } });
  const interpreted = record.interpretedFields as Record<string, unknown>;
  const normalized = record.normalizedFields as NormalizedImport;
  const locator = record.sourceLocator as SourceLocator;
  const warnings = [...list(record.validationErrors), ...list(record.warnings)];
  const recommended = record.matchCandidates.find((candidate) => candidate.recommended) ?? record.matchCandidates[0];
  const alternatives = record.matchCandidates.filter((candidate) => candidate.id !== recommended?.id);
  const sourceLabel = locator.sheet ? `Foglio ${locator.sheet} · riga ${locator.row ?? record.recordIndex}` : locator.page ? `Pagina ${locator.page}` : `Riga ${locator.row ?? record.recordIndex}`;
  const canDecide = !["PUBLISHED", "IGNORED", "NON_COMPARABLE", "CONFIRMED", "NEW_PRODUCT_CONFIRMED"].includes(record.status);
  const isNew = recommended?.matchType === "NEW_PRODUCT" || !recommended?.canonicalProductId;
  return <main>
    {(await searchParams).corretto && <div className="success">Correzione salvata e prezzo normalizzato ricalcolato.</div>}
    <PageHeader eyebrow={`Revisione record · ${sourceLabel}`} title={String(normalized.description ?? interpreted.description ?? "Descrizione da verificare")} description={`${record.importJob.sourceDocument.originalFilename} · ${record.importJob.sourceDocument.supplier?.name ?? "Fornitore da confermare"}`} action={<Link className="secondary-cta" href={`/imports/${id}?filtro=attention`}>Torna alle eccezioni</Link>} />
    <div className="record-review-status"><ImportStatus status={record.status} /><SourceReference locator={record.sourceLocator} />{record.exceptionType && <span className="warning-inline">{exceptionLabels[record.exceptionType] ?? "Dato da verificare"}</span>}</div>

    <section className="record-decision-hero" aria-label="Decisione sul record">
      <article className="source-pane"><p className="eyebrow">Documento</p><h2>{String(interpreted.description ?? record.rawSource)}</h2><pre>{record.rawSource}</pre><strong>{sourceLabel}</strong><Link className="text-link" href={`/imports/documents/${record.importJob.sourceDocument.id}`}>Apri documento originale</Link></article>
      <article className="interpreted-summary"><p className="eyebrow">Dato interpretato</p><h2>{String(normalized.description ?? "Da verificare")}</h2><dl><div><dt>Confezione</dt><dd>{purchaseUomLabel(normalized.purchaseUom)} · {normalized.unitsPerPackage ?? "?"} {consumptionUomLabel(normalized.consumptionUom)}</dd></div><div><dt>Prezzo confezione</dt><dd>{normalized.netPrice == null ? "—" : formatMoney(Number(normalized.netPrice))}</dd></div><div><dt>Prezzo normalizzato</dt><dd>{normalized.comparable && normalized.normalizedPrice != null ? `${formatMoney(Number(normalized.normalizedPrice), 4)} / ${consumptionUomLabel(normalized.consumptionUom)}` : "Non confrontabile"}</dd></div></dl><div className="confidence-inline"><span>Affidabilità</span><Confidence value={Number(record.matchConfidence)} /></div></article>
      <article className="recommended-match"><p className="eyebrow">Match consigliato</p><h2>{recommended?.canonicalProduct?.name ?? "Nessuna corrispondenza affidabile"}</h2>{recommended?.canonicalProduct && <><span>{recommended.canonicalProduct.brand ?? "Marca non indicata"} · {recommended.canonicalProduct.category.name}</span><ul>{list(recommended.reasons).slice(0, 4).map((reason) => <li key={reason}>{reason}</li>)}</ul></>}{recommended?.canonicalProductId && canDecide && <form action={acceptRecord}><input type="hidden" name="jobId" value={id} /><input type="hidden" name="recordId" value={record.id} /><input type="hidden" name="candidateId" value={recommended.id} /><button className="primary-cta">Conferma associazione</button></form>}{!recommended?.canonicalProductId && <span className="watch">Serve una decisione umana</span>}</article>
    </section>

    {warnings.length > 0 && <section className="record-exceptions"><div><p className="eyebrow">Eccezioni</p><h2>{warnings.length === 1 ? "Un elemento richiede attenzione" : `${warnings.length} elementi richiedono attenzione`}</h2></div><ul>{warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></section>}

    {recommended?.canonicalProduct && <section className="match-recommendation"><div className="section-heading"><div><p className="eyebrow">Corrispondenza consigliata</p><h2>{recommended.canonicalProduct.name}</h2><p>{list(recommended.reasons).length} segnali spiegano il suggerimento; le differenze restano visibili.</p></div><Confidence value={Number(recommended.score)} detail={Number(recommended.score) >= .88 ? "Corrispondenza alta" : "Da verificare"} /></div><div className="match-differences">{candidateDifference("Marca", normalized.brand, recommended.canonicalProduct.brand)}{candidateDifference("Confezione", `${normalized.unitsPerPackage ?? "?"} ${consumptionUomLabel(normalized.consumptionUom)}`, recommended.canonicalProduct.packageDescription)}{candidateDifference("EAN", normalized.ean, recommended.canonicalProduct.ean)}{candidateDifference("Unità", purchaseUomLabel(normalized.purchaseUom), purchaseUomLabel(recommended.canonicalProduct.purchaseUom))}</div></section>}

    {alternatives.length > 0 && <details className="match-alternatives"><summary>Alternative possibili · {alternatives.length}</summary><div>{alternatives.map((candidate) => <article key={candidate.id}><div><strong>{candidate.canonicalProduct?.name ?? "Nuovo prodotto"}</strong><span>{matchTypeLabels[candidate.matchType]} · {list(candidate.reasons).slice(0,2).join(" · ")}</span></div><Confidence value={Number(candidate.score)} />{candidate.canonicalProductId && canDecide && <form action={acceptRecord}><input type="hidden" name="jobId" value={id} /><input type="hidden" name="recordId" value={record.id} /><input type="hidden" name="candidateId" value={candidate.id} /><button className="secondary-cta compact">Usa questo prodotto</button></form>}</article>)}</div></details>}

    {canDecide && <details className="compact-correction"><summary>Correggi i dati interpretati</summary><form action={correctAndAcceptRecord}><input type="hidden" name="jobId" value={id} /><input type="hidden" name="recordId" value={record.id} /><label>Descrizione prodotto<input name="description" defaultValue={String(normalized.description ?? "")} required /></label><div><label>Prezzo confezione<input name="netPrice" inputMode="decimal" defaultValue={normalized.netPrice == null ? "" : String(normalized.netPrice)} required /></label><label>Unità per confezione<input name="unitsPerPackage" type="number" min="0.0001" step="0.0001" defaultValue={normalized.unitsPerPackage == null ? "" : String(normalized.unitsPerPackage)} required /></label></div><div><label>Unità acquistata<select name="purchaseUom" defaultValue={String(normalized.purchaseUom ?? "BOX")}><option value="BOX">Confezione</option><option value="CASE">Cartone</option><option value="BOTTLE">Flacone</option><option value="CAN">Tanica</option><option value="PACK">Pacco</option></select></label><label>Unità di consumo<select name="consumptionUom" defaultValue={String(normalized.consumptionUom ?? "PIECE")}><option value="PIECE">Pezzo</option><option value="L">Litro</option><option value="KG">Kg</option><option value="PAIR">Paio</option><option value="ROLL">Rotolo</option><option value="FILTER">Filtro</option></select></label></div><button className="primary-cta">Salva correzione</button></form></details>}

    {canDecide && isNew && <section className="new-product-review"><div><p className="eyebrow">Nessuna corrispondenza</p><h2>Crea un prodotto canonico</h2><p>I campi provengono da {sourceLabel} e devono essere confermati prima della pubblicazione.</p></div><form action={confirmNewProduct}><input type="hidden" name="jobId" value={id} /><input type="hidden" name="recordId" value={record.id} /><label>Nome prodotto<input name="description" defaultValue={String(normalized.description ?? "")} required /></label><label>Categoria<select name="categoryId" required defaultValue=""><option value="" disabled>Seleziona categoria</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Marca<input name="brand" defaultValue={String(normalized.brand ?? "")} /></label><label>GTIN / EAN<input name="ean" defaultValue={String(normalized.ean ?? "")} /></label><label>Codice produttore<input name="manufacturerSku" defaultValue={String(normalized.manufacturerSku ?? "")} /></label><label>Unità acquistata<select name="purchaseUom" defaultValue={String(normalized.purchaseUom ?? "BOX")}><option value="BOX">Confezione</option><option value="CASE">Cartone</option><option value="PACK">Pacco</option><option value="BOTTLE">Flacone</option><option value="CAN">Tanica</option></select></label><label>Contenuto<input name="unitsPerPackage" type="number" min="0.0001" step="0.0001" defaultValue={String(normalized.unitsPerPackage ?? 1)} /></label><label>Unità di consumo<select name="consumptionUom" defaultValue={String(normalized.consumptionUom ?? "PIECE")}><option value="PIECE">Pezzo</option><option value="L">Litro</option><option value="KG">Kg</option><option value="ROLL">Rotolo</option></select></label><button className="primary-cta">Conferma nuovo prodotto</button></form></section>}

    {canDecide && <section className="non-comparable-decision"><div><p className="eyebrow">Se il confronto non è affidabile</p><h2>{!normalized.comparable ? "Manca un dato per normalizzare il prezzo" : "Il record può avere un esito diverso"}</h2><p>{warnings[0] ?? "Scegli esplicitamente come gestire la riga. Nulla viene creato in automatico."}</p></div><div><form action={markRecord}><input type="hidden" name="jobId" value={id} /><input type="hidden" name="recordId" value={record.id} /><button name="decision" value="NON_COMPARABLE" className="secondary-cta">Mantieni non confrontabile</button></form><form action={markRecord}><input type="hidden" name="jobId" value={id} /><input type="hidden" name="recordId" value={record.id} /><button name="decision" value="IGNORED" className="text-button">Ignora riga</button></form></div></section>}

    <details className="provenance-disclosure"><summary><span><strong>Provenienza</strong><small>{record.fieldValues.length} campi tracciati</small></span><span>Mostra dettaglio</span></summary>{record.fieldValues.length > 0 && <DataTable label="Provenienza campi"><thead><tr><th>Campo</th><th>Grezzo</th><th>Interpretato</th><th>Normalizzato</th><th>Correzione umana</th><th>Fonte</th><th>Motore</th></tr></thead><tbody>{record.fieldValues.map((field) => <tr key={field.id}><td>{readableField(field.fieldName)}</td><td>{displayValue(field.rawValue)}</td><td>{presentFieldValue(field.fieldName, field.interpretedValue)}</td><td>{presentFieldValue(field.fieldName, field.normalizedValue)}</td><td>{field.humanValue == null ? "—" : <>{presentFieldValue(field.fieldName, field.humanValue)}<span className="cell-detail">{field.confirmedBy?.name}</span></>}</td><td><SourceReference locator={field.sourceLocator} /></td><td>{interpretationProviderLabel(field.interpretationProvider ?? record.importJob.interpretationProvider)}<span className="cell-detail">{field.providerModel ?? "Regole locali"}</span></td></tr>)}</tbody></DataTable>}</details>
    {record.corrections.length > 0 && <details className="correction-history"><summary>Correzioni manuali · {record.corrections.length}</summary>{record.corrections.map((correction) => <article key={correction.id}><strong>{readableField(correction.fieldName)}</strong><span>{correction.correctedBy.name} · {formatDate(correction.correctedAt)}</span></article>)}</details>}
  </main>;
}
