import Link from "next/link";
import { Metric, PageHeader, StatusIndicator } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { compareOffers, formatMoney, getComparablePrice } from "@/lib/pricing";
import { prisma } from "@/lib/prisma";

export default async function ComparePage() {
  await requireRoles(["PROCUREMENT_MANAGER"]); const products = await prisma.canonicalProduct.findMany({ where: { offers: { some: {} } }, include: { category: true, offers: { include: { supplier: true } } } }); const comparable = products.filter((p) => p.offers.length > 1); const comparisons = comparable.map((product) => ({ product, result: compareOffers(product.offers) })); const supplierCount = new Set(comparable.flatMap((p) => p.offers.map((o) => o.supplierId))).size; const average = comparisons.length ? comparisons.reduce((sum, c) => sum + c.result.spread, 0) / comparisons.length : 0; const opportunity = comparisons.reduce((sum, c) => sum + Math.max(0, c.result.preferred ? getComparablePrice(c.result.preferred) - getComparablePrice(c.result.lowest!) : 0), 0);
  return <main><PageHeader eyebrow="Price intelligence" title="Compare" description="Normalized supplier offers aligned to the same canonical product." /><div className="metrics-grid four"><Metric label="Comparable products" value={comparable.length} /><Metric label="Suppliers represented" value={supplierCount} /><Metric label="Average price spread" value={`${average.toFixed(1)}%`} /><Metric label="Harmonization opportunity" value={formatMoney(opportunity, 4)} detail="Demo estimate · one normalized unit each" /></div><div className="comparison-list">{comparisons.map(({ product, result }) => <article className="compare-card" key={product.id}><header><div><span>{product.category.name}</span><Link href={`/products/${product.id}`}>{product.name}</Link></div><strong>{result.spread.toFixed(1)}% spread</strong></header><div className="offer-bars">{result.sorted.map((offer) => <div key={offer.id} className="offer-bar"><div><b>{offer.supplier.name}</b>{offer.preferred && <StatusIndicator active label="Preferred" />}</div><strong>{formatMoney(getComparablePrice(offer), 4)}</strong></div>)}</div><footer><span>Delta {formatMoney(result.deltaEuro, 4)}</span><b>{result.preferredDelta === 0 ? "Best available" : `Preferred is ${result.preferredDelta.toFixed(1)}% above lowest available`}</b></footer></article>)}</div></main>;
}
