import Link from "next/link";
import { manageCategory } from "@/app/admin-actions";
import { AdminFeedback, AdminPanel } from "@/components/admin-crud";
import { DataTable, EmptyRow, PageHeader } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
export default async function CategoriesPage({searchParams}:{searchParams:Promise<{esito?:string}>}){
 const context=await requireRoles(["PROCUREMENT_MANAGER","PROCUREMENT_ADMIN"]),query=await searchParams,categories=await prisma.category.findMany({include:{_count:{select:{products:true,budgets:true,procurementLimits:true}}},orderBy:{name:"asc"}}),admin=context.roleCode==="PROCUREMENT_ADMIN";
 return <main className="phase2-page phase2-admin"><PageHeader eyebrow="Gestione categorie" title="Categorie" description="Classificazione canonica del catalogo e relativi vincoli referenziali." action={admin?<AdminPanel label="Nuova categoria"><form action={manageCategory} className="admin-crud-form"><input type="hidden" name="intent" value="create"/><label>Codice<input name="code" required minLength={2}/></label><label>Nome<input name="name" required minLength={3}/></label><button className="primary-cta">Crea categoria</button></form></AdminPanel>:undefined}/><AdminFeedback result={query.esito}/><DataTable label="Categorie"><thead><tr><th>Categoria</th><th>Prodotti</th><th>Vincoli</th>{admin&&<th>Gestione</th>}</tr></thead><tbody>{categories.length?categories.map(category=><tr key={category.id}><td><Link className="table-link" href={`/categorie/${category.id}`}>{category.name}</Link><small className="cell-detail">{category.code}</small></td><td>{category._count.products}</td><td>{category._count.budgets+category._count.procurementLimits}</td>{admin&&<td><details className="row-more"><summary>Modifica</summary><form action={manageCategory} className="admin-crud-form"><input type="hidden" name="id" value={category.id}/><label>Codice<input name="code" defaultValue={category.code} required/></label><label>Nome<input name="name" defaultValue={category.name} required/></label><button name="intent" value="update">Salva</button><button className="danger-secondary" name="intent" value="delete">Elimina se inutilizzata</button></form></details></td>}</tr>):<EmptyRow colSpan={admin?4:3}>Nessuna categoria.</EmptyRow>}</tbody></DataTable></main>;
}
