export type NormalizableProduct={purchaseUom:string;unitsPerPackage:unknown;consumptionUom:string|null;consumptionUomLabel:string|null;packageDescription:string|null};
export type NormalizableOffer={unitPrice:unknown;packageSize?:unknown;packageUnit?:string|null};
export type NormalizedPrice={comparable:boolean;purchasePrice:number;purchaseUom:string;packageQuantity:number|null;consumptionUom:string|null;consumptionLabel:string;normalizedQuantity:number|null;normalizedPrice:number|null;purchaseLabel:string;contentLabel:string;normalizedLabel:string;reason?:string};
const purchaseLabels:Record<string,string>={BOX:"confezione",PACK:"confezione",CASE:"cartone",BOTTLE:"flacone",CAN:"tanica",BAG:"sacco",ROLL:"rotolo",PIECE:"pezzo"};
const consumptionLabels:Record<string,string>={PIECE:"pezzo",L:"litro",KG:"kg",ROLL:"rotolo",FILTER:"filtro",PAIR:"paio",M:"metro"};
export function normalizeOfferPrice(product:NormalizableProduct,offer:NormalizableOffer):NormalizedPrice{const purchasePrice=Number(offer.unitPrice),factor=Number(product.unitsPerPackage),purchaseUom=product.purchaseUom||offer.packageUnit||"PACK",consumptionUom=product.consumptionUom,consumptionLabel=product.consumptionUomLabel||consumptionLabels[consumptionUom??""]||"unità",purchaseLabel=purchaseLabels[purchaseUom]||purchaseUom.toLowerCase();if(!Number.isFinite(purchasePrice)||purchasePrice<0)return invalid("Prezzo d’acquisto non valido");if(!consumptionUom||!Number.isFinite(factor)||factor<=0)return {...invalid("Conversione della confezione mancante"),purchasePrice,purchaseUom,purchaseLabel,consumptionLabel,contentLabel:product.packageDescription??"Contenuto non definito"};const normalizedPrice=purchasePrice/factor;return{comparable:true,purchasePrice,purchaseUom,packageQuantity:factor,consumptionUom,consumptionLabel,normalizedQuantity:factor,normalizedPrice,purchaseLabel,contentLabel:product.packageDescription??`${formatQuantity(factor)} ${plural(consumptionLabel,factor)}`,normalizedLabel:`${formatCurrency(normalizedPrice,4)} / ${consumptionLabel}`};}
function invalid(reason:string):NormalizedPrice{return{comparable:false,purchasePrice:0,purchaseUom:"",packageQuantity:null,consumptionUom:null,consumptionLabel:"unità",normalizedQuantity:null,normalizedPrice:null,purchaseLabel:"unità d’acquisto",contentLabel:"Contenuto non definito",normalizedLabel:"Non direttamente confrontabile",reason};}
export function formatQuantity(value:number){return new Intl.NumberFormat("it-IT",{maximumFractionDigits:3}).format(value)}
export function formatCurrency(value:number,digits=2){return new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)}
export function plural(label:string,value:number){if(value===1)return label;return({pezzo:"pezzi",litro:"litri",filtro:"filtri",rotolo:"rotoli",paio:"paia",metro:"metri"} as Record<string,string>)[label]??label}
export function assertComparable(a:NormalizedPrice,b:NormalizedPrice){return a.comparable&&b.comparable&&a.consumptionUom===b.consumptionUom}
