import "dotenv/config";
import { PrismaClient, type IssueType, type RequisitionStatus } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { seedSmartImports } from "./seed-smart-import";

const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });
const now = new Date("2026-08-30T09:00:00Z");
const day = 86_400_000;
const money = (n: number) => Math.round(n * 100) / 100;

const catalog = [
  ["DISPOSABLES","Dispositivi monouso","Guanti",["Guanto nitrile senza polvere M — 100 pezzi","Guanto nitrile senza polvere L — 100 pezzi","Guanto nitrile blu S — 100 pezzi","Mascherina chirurgica tipo IIR — 50 pezzi","Garza sterile 10 × 10 cm — 100 pezzi","Cerotto in rotolo 5 m × 2,5 cm","Siringa sterile 10 ml — 100 pezzi","Ago ipodermico 21G — 100 pezzi","Bicchiere monouso 200 ml — 100 pezzi","Telino assorbente 60 × 90 cm — 30 pezzi","Copriscarpa monouso — 100 pezzi","Camice visitatore TNT — 10 pezzi","Rotolo lettino medico 60 cm"]],
  ["INCONTINENCE","Incontinenza","Assorbenza",["Pannolone mutandina giorno M — 30 pezzi","Pannolone mutandina notte M — 30 pezzi","Pannolone mutandina giorno L — 30 pezzi","Pannolone mutandina notte L — 30 pezzi","Pannolone a cintura M — 28 pezzi","Pannolone a cintura L — 28 pezzi","Pants assorbente M — 14 pezzi","Pants assorbente L — 14 pezzi","Pants assorbente XL — 14 pezzi","Sagomato anatomico maxi — 30 pezzi","Traversa 60 × 60 cm — 30 pezzi","Traversa 60 × 90 cm — 30 pezzi","Mutandina elasticizzata rete L — 25 pezzi"]],
  ["CLEANING","Detergenza","Superfici",["Detergente professionale superfici — 5 L","Disinfettante superfici pronto uso — 750 ml","Detergente pavimenti agrumato — 5 L","Sgrassatore cucina — 750 ml","Detergente vetri — 750 ml","Candeggina professionale — 5 L","Detersivo lavatrice liquido — 10 L","Ammorbidente concentrato — 5 L","Detergente lavastoviglie — 6 kg","Brillantante lavastoviglie — 5 L","Sacchi rifiuti 110 L — 20 pezzi","Panno microfibra blu — 10 pezzi","Spugna abrasiva professionale — 10 pezzi"]],
  ["PERSONAL_CARE","Igiene persona","Cura corpo",["Sapone mani delicato — 5 L","Bagno doccia pH neutro — 1 L","Shampoo delicato — 1 L","Crema barriera protettiva — 200 ml","Olio detergente — 500 ml","Salviette detergenti — 80 pezzi","Spugne saponate monouso — 20 pezzi","Dentifricio delicato — 75 ml","Spazzolino morbido","Deodorante roll-on neutro — 50 ml","Crema corpo idratante — 500 ml","Schiuma detergente senza risciacquo — 400 ml","Manopola presaponata — 20 pezzi"]],
  ["FOOD","Alimentari","Dispensa",["Pasta di semola formato corto — 5 kg","Riso parboiled — 5 kg","Passata di pomodoro — 6 × 700 g","Olio extravergine di oliva — 5 L","Fette biscottate monoporzione — 120 pezzi","Confettura albicocca monoporzione — 100 pezzi","Biscotti secchi monoporzione — 100 pezzi","Tè deteinato — 100 filtri","Camomilla — 100 filtri","Brodo vegetale granulare — 1 kg","Farina tipo 00 — 5 kg","Zucchero semolato — 10 × 1 kg","Acqua naturale — 6 × 1,5 L"]],
  ["STATIONERY","Cancelleria","Ufficio",["Carta A4 80 g — 5 risme","Penna a sfera blu — 50 pezzi","Pennarello indelebile nero — 12 pezzi","Cartellina tre lembi blu — 25 pezzi","Busta a foratura A4 — 100 pezzi","Etichette adesive 70 × 37 mm — 2400 pezzi","Toner laser nero compatibile","Post-it 76 × 76 mm — 12 blocchi","Registro protocollo A4","Punti metallici 24/6 — 10 scatole","Nastro adesivo trasparente — 10 rotoli","Buste bianche 11 × 23 cm — 500 pezzi","Raccoglitore protocollo dorso 8 cm"]],
  ["MAINTENANCE","Manutenzione","Ricambi",["Lampadina LED E27 10 W — 10 pezzi","Batteria alcalina AA — 24 pezzi","Batteria alcalina AAA — 24 pezzi","Nastro isolante nero — 10 rotoli","Silicone sanitario bianco — 12 cartucce","Filtro climatizzatore universale","Rubinetto temporizzato lavabo","Flessibile doccia rinforzato 150 cm","Set cacciaviti isolati — 6 pezzi","Guarnizioni assortite — 100 pezzi","Spray lubrificante tecnico — 400 ml","Fascette nylon 200 mm — 100 pezzi","Multipresa 6 posti con interruttore"]],
  ["PPE","DPI","Protezione",["Mascherina FFP2 NR — 20 pezzi","Occhiale protettivo trasparente","Visiera protettiva regolabile","Camice protettivo tipo 4B L","Camice protettivo tipo 4B XL","Cuffia monouso blu — 100 pezzi","Grembiule impermeabile — 50 pezzi","Calzatura antiscivolo bianca 39","Calzatura antiscivolo bianca 42","Guanto antitaglio livello C — 12 paia","Tappi auricolari — 200 paia","Semimaschera riutilizzabile","Filtro combinato ABEK — 4 pezzi"]],
  ["NUTRITION","Nutrizione speciale","Integratori",["Bevanda nutrizionale vaniglia 200 ml","Bevanda nutrizionale cacao 200 ml","Addensante istantaneo 300 g","Preparato proteico neutro 400 g","Acqua gelificata limone 24 vasetti","Dessert iperproteico vaniglia 4 pezzi","Crema cereali istantanea 500 g","Purea mela monoporzione 48 pezzi","Biscotto solubile 600 g","Integratore fibra 250 g","Bevanda reidratante arancia 500 ml","Preparato budino proteico 400 g","Maltodestrine polvere 500 g"]],
  ["LINEN","Biancheria","Tessili",["Lenzuolo piano cotone bianco","Lenzuolo con angoli singolo","Federa cotone bianco 50 × 80 cm","Traversa lavabile impermeabile","Telo bagno spugna bianco","Asciugamano viso spugna bianco","Coperta ignifuga singola","Coprimaterasso impermeabile","Bavaglia adulto lavabile","Sacco lavanderia idrosolubile","Divisa operatore casacca blu M","Divisa operatore pantalone blu M","Tenda doccia antibatterica"]],
  ["KITCHEN","Cucina","Attrezzature cucina",["Contenitore gastronorm 1/2 inox","Coperchio gastronorm 1/2","Caraffa graduata 2 litri","Tagliere HACCP rosso","Tagliere HACCP verde","Coltello cucina professionale 20 cm","Mestolo inox 30 cm","Vassoio isotermico completo","Bicchiere policarbonato 250 ml","Piatto piano melamina bianco","Pellicola alimentare professionale","Carta forno 50 metri","Guanto forno termico lungo"]],
  ["MOBILITY","Ausili","Mobilità",["Bastone regolabile anatomico","Tripode regolabile leggero","Deambulatore pieghevole due ruote","Cuscino antidecubito viscoelastico","Alzawater con braccioli","Sedia doccia regolabile","Tavolino servitore inclinabile","Cintura trasferimento assistito","Pedaliera riabilitativa compatta","Disco girevole trasferimento","Maniglione bagno 45 cm","Tappeto antiscivolo doccia","Protezione sponda letto imbottita"]],
] as const;
const brands = ["DemoCare","SereniPlus","CleanDemo","VitaSoft","TavolaViva","OfficeLeaf","Fixora","SafeLine","NutriVivo","TessilCare","CucinaPro","Mobilis"];
const supplierNames = ["Alfa Medical","CareSupply","CleanPro Italia","NordCare Distribution","Vita Facility","Linea Igiene","Medika Network","Servizi & Forniture","EcoSan Pro","Tavola Comune","Office Bridge","ManuTech","Protezione Più","Adriatica Supply","Piemonte Medical","Emilia Facility","Lombarda Cura","Delta Professional","Aurora Trade","Unione Forniture","NutriSalus","Tessili Comunità","Kitchen Service","Mobilità Serena","Centro Ausili Italia",...Array.from({length:50},(_,index)=>`Forniture Regionali Demo ${String(index+26).padStart(3,"0")}`)];

function packaging(name:string,category:string){const lower=name.toLowerCase();let quantity=1,uom="PIECE",label="pezzo",purchase="PACK";const pieces=lower.match(/(?:—|-)\s*(\d+)\s*(?:pezzi|filtri|paia|vasetti|blocchi|rotoli|cartucce|risme|scatole)/);if(pieces){quantity=Number(pieces[1]);uom=lower.includes("filtri")?"FILTER":lower.includes("paia")?"PAIR":lower.includes("rotoli")?"ROLL":"PIECE";label=uom==="FILTER"?"filtro":uom==="PAIR"?"paio":uom==="ROLL"?"rotolo":"pezzo";}const multi=lower.match(/(\d+)\s*[×x]\s*([\d,.]+)\s*(l|ml|kg|g)/);const single=lower.match(/(?:—|-)\s*([\d,.]+)\s*(l|ml|kg|g)\b/);const measure=multi??single;if(measure){const count=multi?Number(measure[1]):1,value=Number((multi?measure[2]:measure[1]).replace(",",".")),unit=multi?measure[3]:measure[2];if(unit==="l"||unit==="ml"){quantity=count*value*(unit==="ml"?.001:1);uom="L";label="litro";purchase=multi?"CASE":"BOTTLE"}else{quantity=count*value*(unit==="g"?.001:1);uom="KG";label="kg";purchase=multi?"CASE":"PACK"}}if(lower.includes("tanica")||(/\b5 l\b/.test(lower)&&category==="CLEANING"))purchase="CAN";if(lower.includes("confezione")||pieces)purchase="BOX";return{purchaseUom:purchase,unitsPerPackage:quantity,consumptionUom:uom,consumptionUomLabel:label,packageDescription:uom==="L"?`${quantity.toLocaleString("it-IT")} litri per ${purchase==="CASE"?"cartone":"confezione"}`:uom==="KG"?`${quantity.toLocaleString("it-IT")} kg per confezione`:`Confezione da ${quantity} ${quantity===1?label:label==="pezzo"?"pezzi":label==="filtro"?"filtri":label==="paio"?"paia":label+"i"}`};}
function attributes(name:string,code:string,p:number,pack:ReturnType<typeof packaging>){const size=/\b(XL|L|M|S|39|42)\b/.exec(name)?.[1];if(code==="DISPOSABLES")return{material:name.toLowerCase().includes("nitrile")?"Nitrile":"TNT medicale",size:size??"Unica",color:name.toLowerCase().includes("blu")?"Blu":"Azzurro",powderFree:true,aql:"1,5",latexFree:true,sterile:name.toLowerCase().includes("sterile"),ceMarking:"CE",piecesPerPackage:pack.unitsPerPackage};if(code==="CLEANING")return{volumeLiters:pack.consumptionUom==="L"?pack.unitsPerPackage:null,ph:7+(p%4),dilution:p%3===0?"1:50":"Pronto uso",surfaces:["Pavimenti","Superfici lavabili"],fragrance:p%2?"Neutra":"Agrumi",haccp:p%3===0};if(code==="INCONTINENCE")return{size:size??"M",absorption:p%2?"Notte":"Giorno",piecesPerPackage:pack.unitsPerPackage,latexFree:true};if(code==="PPE")return{material:"Materiale tecnico certificato",size:size??"Unica",ceMarking:"CE",certified:true,piecesPerPackage:pack.unitsPerPackage};if(code==="FOOD")return{weightKg:pack.consumptionUom==="KG"?pack.unitsPerPackage:null,volumeLiters:pack.consumptionUom==="L"?pack.unitsPerPackage:null,filtersPerPackage:pack.consumptionUom==="FILTER"?pack.unitsPerPackage:null,storage:"Luogo fresco e asciutto"};return{professionalUse:true,storage:"Ambiente asciutto",piecesPerPackage:pack.consumptionUom==="PIECE"?pack.unitsPerPackage:null};}

async function clear() {
  await prisma.importFieldCorrection.deleteMany(); await prisma.importedFieldValue.deleteMany(); await prisma.productMatchCandidate.deleteMany();
  await prisma.operationalAttachment.deleteMany(); await prisma.procurementLimit.deleteMany();
  await prisma.approvalDelegation.deleteMany(); await prisma.outOfCatalogRequest.deleteMany(); await prisma.shoppingListItem.deleteMany(); await prisma.shoppingList.deleteMany(); await prisma.favorite.deleteMany();
  await prisma.auditEvent.deleteMany(); await prisma.qualityIssue.deleteMany(); await prisma.receiptLine.deleteMany(); await prisma.receipt.deleteMany();
  await prisma.purchaseOrderLine.deleteMany(); await prisma.purchaseOrder.deleteMany(); await prisma.approvalRequest.deleteMany(); await prisma.purchaseRequisitionLine.deleteMany(); await prisma.purchaseRequisition.deleteMany();
  await prisma.cartLine.deleteMany(); await prisma.cart.deleteMany(); await prisma.budget.deleteMany(); await prisma.offerPriceHistory.deleteMany(); await prisma.supplierOffer.deleteMany(); await prisma.priceList.deleteMany();
  await prisma.importedRecord.deleteMany(); await prisma.importJob.deleteMany(); await prisma.sourceDocument.deleteMany();
  await prisma.canonicalProduct.deleteMany(); await prisma.category.deleteMany(); await prisma.supplier.deleteMany(); await prisma.userAssignment.deleteMany(); await prisma.role.deleteMany(); await prisma.user.deleteMany();
  await prisma.costCenter.deleteMany(); await prisma.facility.deleteMany(); await prisma.area.deleteMany(); await prisma.legalEntity.deleteMany(); await prisma.organization.deleteMany();
}

async function main() {
  await clear();
  const anteo=await prisma.organization.create({data:{name:"Anteo Demo"}}); const coop=await prisma.organization.create({data:{name:"Coopselios Demo"}});
  const entities=await Promise.all([["Anteo Impresa Sociale Demo",anteo.id],["Anteo Servizi Demo",anteo.id],["Coopselios Nord Demo",coop.id],["Coopselios Centro Demo",coop.id]].map(([name,organizationId])=>prisma.legalEntity.create({data:{name,organizationId}})));
  const areas=await Promise.all([["Area Piemonte",0],["Area Lombardia",0],["Area Liguria",1],["Area Emilia-Romagna",2],["Area Veneto",2],["Area Toscana",3]].map(([name,e])=>prisma.area.create({data:{name:String(name),legalEntityId:entities[Number(e)].id}})));
  const facilityData:Array<readonly [string,number]>=[["RSA Aurora",0],["Residenza San Michele",0],["Casa Serena",0],["Villa Serena",1],["Residenza Naviglio",1],["Casa Brianza",1],["Centro Levante",2],["Villa degli Ulivi",2],["Residenza del Porto",2],["RSA Giardini",3],["Residenza Ducale",3],["Casa del Reno",3],["Villa Laguna",4],["Residenza Arena",4],["Casa Marca",4],["Villa Arno",5],["Residenza Medicea",5],["Casa delle Colline",5]];
  for(let index=0;index<84;index+=1)facilityData.push([`Struttura territoriale demo ${String(index+19).padStart(3,"0")}`,index<42?index%3:3+index%3]);
  const cities=["Torino","Novara","Asti","Milano","Pavia","Monza","Genova","Savona","La Spezia","Reggio Emilia","Parma","Bologna","Venezia","Verona","Treviso","Firenze","Prato","Siena"];
  const facilities=await Promise.all(facilityData.map(([name,a],i)=>prisma.facility.create({data:{name,areaId:areas[a].id,address:"Via delle Comunità "+(i+1)+", "+cities[i%cities.length]}})));
  const centers=[]; for(let i=0;i<facilities.length;i++){centers.push(await prisma.costCenter.create({data:{facilityId:facilities[i].id,code:"CC-"+String(i+1).padStart(3,"0"),name:"Assistenza e cura"}})); if(i<9) centers.push(await prisma.costCenter.create({data:{facilityId:facilities[i].id,code:"SG-"+String(i+1).padStart(3,"0"),name:"Servizi generali"}}));}
  const roleDefs=[["RSA_DIRECTOR","RSA Director"],["AREA_MANAGER","Area Manager"],["PROCUREMENT_MANAGER","Joint Procurement Manager"],["PROCUREMENT_ADMIN","Procurement Administrator"],["FINANCE_CONTROLLER","Finance Controller"],["EXECUTIVE_SPONSOR","Executive Sponsor"]] as const;
  const roles=Object.fromEntries(await Promise.all(roleDefs.map(async ([code,name])=>[code,await prisma.role.create({data:{code,name,description:name+" demo"}})])));
  const userDefs=[["Lucia Ferri","lucia.ferri@demo.local"],["Andrea Riva","andrea.riva@demo.local"],["Giulia Bianchi","giulia.bianchi@demo.local"],["Marco Villa","marco.villa@demo.local"],["Elena Conti","elena.conti@demo.local"],["Davide Romano","davide.romano@demo.local"]] as const;
  const users=await Promise.all(userDefs.map(([name,email])=>prisma.user.create({data:{name,email}})));
  const facilityRequesters=await Promise.all([["Paola Neri","paola.neri@demo.local"],["Roberto Sala","roberto.sala@demo.local"],["Marta De Luca","marta.deluca@demo.local"],["Stefano Greco","stefano.greco@demo.local"],["Chiara Fontana","chiara.fontana@demo.local"]].map(([name,email])=>prisma.user.create({data:{name,email}})));
  void facilityRequesters;
  const assignDefs=[[0,"RSA_DIRECTOR","FACILITY",facilities[0].id,5000],[1,"AREA_MANAGER","AREA",areas[0].id,20000],[2,"PROCUREMENT_MANAGER","ORGANIZATION",anteo.id,50000],[3,"PROCUREMENT_ADMIN","ORGANIZATION",anteo.id,null],[4,"FINANCE_CONTROLLER","ORGANIZATION",anteo.id,null],[5,"EXECUTIVE_SPONSOR","ORGANIZATION",anteo.id,null]] as const;
  const assignments=await Promise.all(assignDefs.map(([u,r,scopeType,scopeId,approvalLimit])=>prisma.userAssignment.create({data:{userId:users[u].id,roleId:roles[r].id,organizationId:anteo.id,scopeType,scopeId,approvalLimit}})));
  const suppliers=await Promise.all(supplierNames.map((name,i)=>prisma.supplier.create({data:{name,vatNumber:"IT"+String(10000000001+i),contactEmail:"ordini"+(i+1)+"@supplier.demo",contactPhone:"+39 011 555 "+(1000+i),address:"Via Fornitori Demo "+(i+1)+", Torino",paymentTerms:i%3===0?"Bonifico 60 giorni data fattura":"Bonifico 30 giorni data fattura",deliveryTerms:"Franco destino",minimumOrderValue:150+i%5*50,freeShippingThreshold:500+i%4*250,commercialContact:{name:"Sara Demo",email:`commerciale${i+1}@supplier.demo`,phone:`+39 011 410 ${1100+i}`},orderContact:{name:"Ufficio ordini",email:`ordini${i+1}@supplier.demo`,phone:`+39 011 420 ${1200+i}`},qualityContact:{name:"Qualità forniture",email:`qualita${i+1}@supplier.demo`,phone:`+39 011 430 ${1300+i}`},certificationPath:"/documents/certificazione-demo.pdf",commercialDocumentPath:"/documents/dichiarazione-conformita-demo.pdf",qualityDocumentPath:"/documents/scheda-tecnica-demo.pdf",active:true}})));
  for (let index=0; index<suppliers.length; index+=1) await prisma.supplier.update({where:{id:suppliers[index].id},data:{shippingFeeBelowThreshold:18+index%4*4,surchargeBelowMinimum:index%3===0?12:null,currency:"EUR"}});
  const categories=await Promise.all(catalog.map(([code,name])=>prisma.category.create({data:{code,name}})));
  const lists=await Promise.all([...suppliers,...suppliers.slice(0,5)].map((s,i)=>prisma.priceList.create({data:{name:s.name+" — "+(i<suppliers.length?"Listino operativo 2026":"Revisione estate 2026"),supplierId:s.id,validFrom:new Date(i<suppliers.length?"2026-01-01":"2026-07-01"),validUntil:new Date("2026-12-31"),active:true,sourceFile:"listino-"+String(i+1).padStart(2,"0")+"-2026.xlsx"}})));
  // The first five suppliers have an explicit, non-destructive second
  // version. Smart Import and the video demo can therefore explain old/new
  // lineage before creating an additional imported version.
  for(let index=0;index<5;index+=1){
    await prisma.priceList.update({where:{id:lists[index].id},data:{active:false}});
    lists[suppliers.length+index]=await prisma.priceList.update({where:{id:lists[suppliers.length+index].id},data:{version:2,previousVersionId:lists[index].id}});
  }
  const products=[]; const offers=[];
  for(let c=0;c<catalog.length;c++) for(let p=0;p<catalog[c][3].length;p++){
    const name=catalog[c][3][p],pack=packaging(name,catalog[c][0]); const base=2.5+c*2.2+p*.73; const product=await prisma.canonicalProduct.create({data:{name,description:name+". Referenza professionale demo.",shortDescription:"Selezionato per uso professionale in struttura.",longDescription:"Referenza demo con confezionamento, confronto fornitori e tracciabilità documentale verificabili.",brand:brands[c],manufacturer:brands[c]+" Manufacturing Demo",manufacturerSku:catalog[c][0].slice(0,3)+"-"+String(p+1).padStart(3,"0"),ean:"8001"+c+String(p).padStart(7,"0"),uom:pack.purchaseUom,purchaseUom:pack.purchaseUom,unitsPerPackage:pack.unitsPerPackage,consumptionUom:pack.consumptionUom,consumptionUomLabel:pack.consumptionUomLabel,categoryId:categories[c].id,subcategory:catalog[c][2],packageDescription:pack.packageDescription,technicalAttributes:attributes(name,catalog[c][0],p,pack),imagePath:"/products/"+catalog[c][0].toLowerCase()+".svg",datasheetPath:p<7?"/documents/scheda-tecnica-demo.pdf":null,safetySheetPath:c===2&&p<7?"/documents/scheda-sicurezza-demo.pdf":null,certificationPath:[0,7].includes(c)&&p<7?"/documents/certificazione-demo.pdf":null,declarationPath:p<5?"/documents/dichiarazione-conformita-demo.pdf":null,active:true}}); products.push(product);
    for(let o=0;o<2;o++){const si=(c*3+p+o*5)%19; const price=money(base*(o?1.08+(p%4)*.025:1)); const normalized=money(price/Number(product.unitsPerPackage)); const offer=await prisma.supplierOffer.create({data:{supplierId:suppliers[si].id,canonicalProductId:product.id,priceListId:lists[si].id,supplierSku:String(si+1).padStart(2,"0")+"-"+catalog[c][0].slice(0,3)+"-"+String(p+1).padStart(3,"0"),packageSize:product.unitsPerPackage,packageUnit:product.uom,unitPrice:price,normalizedUnitPrice:normalized,moq:o?2:1,leadTimeDays:2+(p+o*3)%9,taxRate:c===4?10:22,validFrom:new Date("2026-01-01"),validUntil:new Date("2026-12-31"),preferred:o===0,active:true,availabilityStatus:p%11===0&&o===1?"LIMITED":"IN_STOCK",contractReference:o===0?"CTR-2026-"+catalog[c][0]:null}}); offers.push(offer); await prisma.offerPriceHistory.createMany({data:[.94,.97,1].map((m,k)=>({supplierOfferId:offer.id,price:money(price*m),normalizedPrice:money(normalized*m),effectiveAt:new Date(2026,k*3,1)}))});}
  }
  const baseProducts=[...products];
  for(let variant=1;variant<=4;variant+=1) for(let index=0;index<baseProducts.length;index+=1){
    const source=baseProducts[index],product=await prisma.canonicalProduct.create({data:{name:`${source.name} · variante ${variant+1}`,description:source.description,shortDescription:source.shortDescription,longDescription:source.longDescription,brand:source.brand,manufacturer:source.manufacturer,manufacturerSku:`${source.manufacturerSku}-V${variant+1}`,ean:null,uom:source.uom,purchaseUom:source.purchaseUom,unitsPerPackage:source.unitsPerPackage,consumptionUom:source.consumptionUom,consumptionUomLabel:source.consumptionUomLabel,categoryId:source.categoryId,subcategory:source.subcategory,packageDescription:source.packageDescription,technicalAttributes:source.technicalAttributes??undefined,imagePath:source.imagePath,datasheetPath:index%9===0?source.datasheetPath:null,safetySheetPath:index%17===0?source.safetySheetPath:null,certificationPath:index%13===0?source.certificationPath:null,declarationPath:index%19===0?source.declarationPath:null,active:true}});products.push(product);
    for(let offerIndex=0;offerIndex<3;offerIndex+=1){const supplierIndex=(index*7+variant*13+offerIndex*17)%suppliers.length,unitPrice=money((2.8+(index%31)*.64+variant*.37)*(1+offerIndex*.055)),normalized=money(unitPrice/Number(product.unitsPerPackage));const offer=await prisma.supplierOffer.create({data:{supplierId:suppliers[supplierIndex].id,canonicalProductId:product.id,priceListId:lists[supplierIndex].id,supplierSku:`NET-${String(index+1).padStart(4,"0")}-V${variant+1}-${offerIndex+1}`,packageSize:product.unitsPerPackage,packageUnit:product.uom,unitPrice,normalizedUnitPrice:normalized,moq:1+offerIndex,leadTimeDays:2+(index+offerIndex)%12,taxRate:index%11===0?10:22,validFrom:new Date("2026-01-01"),validUntil:new Date("2026-12-31"),preferred:offerIndex===0,active:true,availabilityStatus:index%23===0&&offerIndex===2?"LIMITED":"IN_STOCK",contractReference:offerIndex===0?`CTR-2026-NET-${variant}`:null}});offers.push(offer);await prisma.offerPriceHistory.createMany({data:[.94,.97,1].map((multiplier,point)=>({supplierOfferId:offer.id,price:money(unitPrice*multiplier),normalizedPrice:money(normalized*multiplier),effectiveAt:new Date(2026,point*3,1)}))});}
  }
  for(let i=0;i<products.length;i++){const product=products[i],si=(i*7+11)%suppliers.length,price=money((3+(i%47)*.31)*1.11),normalized=money(price/Number(product.unitsPerPackage));const offer=await prisma.supplierOffer.create({data:{supplierId:suppliers[si].id,canonicalProductId:product.id,priceListId:lists[si].id,supplierSku:"ALT-"+String(i+1).padStart(4,"0"),packageSize:product.unitsPerPackage,packageUnit:product.uom,unitPrice:price,normalizedUnitPrice:normalized,moq:2,leadTimeDays:4+i%8,taxRate:i%12===4?10:22,validFrom:new Date("2026-07-01"),validUntil:new Date("2026-12-31"),preferred:false,active:true,availabilityStatus:i%13===0?"LIMITED":"IN_STOCK"}});offers.push(offer);await prisma.offerPriceHistory.createMany({data:[.92,.96,1].map((m,k)=>({supplierOfferId:offer.id,price:money(price*m),normalizedPrice:money(normalized*m),effectiveAt:new Date(2026,k*3,1)}))});}
  const anteoAreaIds=new Set(areas.slice(0,3).map(area=>area.id));
  for(let i=0;i<facilities.length;i++){const f=facilities[i],areaIndex=areas.findIndex(area=>area.id===f.areaId),organizationId=anteoAreaIds.has(f.areaId)?anteo.id:coop.id,entityIndex=areaIndex<2?0:areaIndex===2?1:areaIndex<5?2:3;await prisma.budget.create({data:{organizationId,legalEntityId:entities[entityIndex].id,areaId:f.areaId,facilityId:f.id,costCenterId:centers.find(x=>x.facilityId===f.id)!.id,categoryId:categories[i%categories.length].id,periodStart:new Date("2026-01-01"),periodEnd:new Date("2026-12-31"),approvedAmount:240000+(i%9)*28000,actualAmount:95000+(i%11)*12000,status:"ACTIVE"}});}
  await prisma.procurementLimit.createMany({data:[{organizationId:anteo.id,facilityId:facilities[0].id,canonicalProductId:products[0].id,limitType:"MONETARY",periodStart:new Date("2026-09-01"),periodEnd:new Date("2026-09-30T23:59:59.999Z"),maximumAmount:1800},{organizationId:anteo.id,facilityId:facilities[0].id,canonicalProductId:products[0].id,limitType:"QUANTITY",periodStart:new Date("2026-09-01"),periodEnd:new Date("2026-09-30T23:59:59.999Z"),maximumQuantity:10000,quantityUom:"pezzi"},{organizationId:anteo.id,facilityId:facilities[0].id,categoryId:categories[2].id,limitType:"MONETARY",periodStart:new Date("2026-09-01"),periodEnd:new Date("2026-09-30T23:59:59.999Z"),maximumAmount:12000}]});
  const historyProducts=products.slice(0,40);for(const product of historyProducts){const productOffers=offers.filter(o=>o.canonicalProductId===product.id);for(const offer of productOffers){await prisma.offerPriceHistory.deleteMany({where:{supplierOfferId:offer.id}});await prisma.offerPriceHistory.createMany({data:Array.from({length:12},(_,month)=>{const current=Number(offer.unitPrice),factor=Number(product.unitsPerPackage),season=1.08-month*.006+(month%4===0?.012:0);return{supplierOfferId:offer.id,price:money(current*season),normalizedPrice:current*season/factor,effectiveAt:new Date(2025,8+month,1)}})});}}
  const issueTypes:IssueType[]=["MISSING","DAMAGED","WRONG_ITEM","QUALITY","PACKAGING"];
  const requisitionCount=520,approvedCount=420;
  for(let i=0;i<requisitionCount;i++){const facilityIndex=i%facilities.length,facility=facilities[facilityIndex],organizationId=anteoAreaIds.has(facility.areaId)?anteo.id:coop.id,center=centers.find(x=>x.facilityId===facility.id)!,offer=offers[(i*3)%offers.length],product=products.find(candidate=>candidate.id===offer.canonicalProductId)!,quantity=5+i%18,subtotal=money(Number(offer.unitPrice)*quantity),tax=money(subtotal*Number(offer.taxRate)/100),total=money(subtotal+tax),approved=i<approvedCount,status:RequisitionStatus=approved?"APPROVED":i<490?"PENDING_APPROVAL":i<505?"REJECTED":"CLARIFICATION_REQUESTED",supplier=suppliers.find(s=>s.id===offer.supplierId)!,ageDays=approved?35+(i*13)%330:status==="PENDING_APPROVAL"?1+(i*7)%32:5+(i*11)%50,submittedAt=new Date(now.getTime()-ageDays*day),createdAt=new Date(submittedAt.getTime()-day),requiredByDate=new Date(submittedAt.getTime()+(10+i%6)*day),decisionAt=new Date(submittedAt.getTime()+day),issuedAt=new Date(submittedAt.getTime()+2*day),expectedDeliveryDate=new Date(submittedAt.getTime()+10*day),receivedAt=new Date(submittedAt.getTime()+11*day),requesterId=facilityIndex===0?users[0].id:facilityRequesters[i%facilityRequesters.length].id;
    const availableBudget=42000+(facilityIndex%12)*3500-(i%9)*1200;
    const req=await prisma.purchaseRequisition.create({data:{requisitionNumber:"PR-2026-"+String(i+1).padStart(6,"0"),requesterId,organizationId,facilityId:facility.id,costCenterId:center.id,status,subtotal,taxTotal:tax,total,justification:i%4===0?"Ripristino scorta minima di reparto":null,createdAt,requiredByDate,policyDecision:i%5===0?"AREA_MANAGER_APPROVAL":"AUTO_APPROVE",policyExplanation:i%5===0?"Importo soggetto a revisione Area Manager.":"Acquisto da catalogo entro budget e limite autonomo.",policyEvaluation:{rules:["CATALOG","WITHIN_BUDGET"],seeded:true},budgetBefore:availableBudget,budgetAfter:availableBudget-total,submittedAt,approvedAt:approved?decisionAt:null,rejectedAt:status==="REJECTED"?decisionAt:null,lines:{create:{canonicalProductId:product.id,supplierOfferId:offer.id,descriptionSnapshot:product.name,supplierSnapshot:supplier.name,supplierSkuSnapshot:offer.supplierSku,quantity,unitPrice:offer.unitPrice,normalizedUnitPrice:offer.normalizedUnitPrice,taxRate:offer.taxRate,lineTotal:subtotal}}}});
    if(i%5===0) await prisma.approvalRequest.create({data:{requisitionId:req.id,approverUserId:users[1].id,approverAssignmentId:assignments[1].id,status:approved?"APPROVED":status==="REJECTED"?"REJECTED":status==="CLARIFICATION_REQUESTED"?"CLARIFICATION_REQUESTED":"PENDING",level:1,reason:"Sopra limite autonomo della struttura",decisionNote:approved?"Approvato nel contesto del budget disponibile.":null,requestedAt:submittedAt,decidedAt:approved?decisionAt:null}});
    if(approved){const po=await prisma.purchaseOrder.create({data:{poNumber:"PO-2026-"+String(i+1).padStart(6,"0"),requisitionId:req.id,supplierId:supplier.id,organizationId,facilityId:facility.id,deliveryLocation:facility.address!,status:i<5?"ISSUE":i<15?"RECEIVED":i<18?"PARTIALLY_RECEIVED":"ISSUED",subtotal,taxTotal:tax,total,issuedAt,expectedDeliveryDate,supplierAcknowledgedAt:new Date(issuedAt.getTime()+day),lines:{create:{canonicalProductId:product.id,descriptionSnapshot:product.name,supplierSkuSnapshot:offer.supplierSku,quantity,unitPrice:offer.unitPrice,taxRate:offer.taxRate,lineTotal:subtotal}}},include:{lines:true}});
      if(i<15){const received=i<5?quantity-1:quantity;const receipt=await prisma.receipt.create({data:{receiptNumber:"GR-2026-"+String(i+1).padStart(6,"0"),purchaseOrderId:po.id,facilityId:facility.id,receivedById:users[0].id,receivedAt,status:i<5?"WITH_ISSUES":"COMPLETE",notes:i<5?"Ricezione con anomalia registrata.":"Consegna verificata.",lines:{create:{purchaseOrderLineId:po.lines[0].id,quantityOrdered:quantity,quantityReceived:received,quantityAccepted:i<5?received-1:received,quantityRejected:i<5?1:0}}},include:{lines:true}});if(i<5)await prisma.qualityIssue.create({data:{receiptLineId:receipt.lines[0].id,purchaseOrderLineId:po.lines[0].id,issueType:issueTypes[i],severity:i===3?"HIGH":"MEDIUM",affectedQuantity:1,description:["Unità mancante.","Confezione danneggiata.","Articolo errato.","Qualità da verificare.","Imballo compromesso."][i],openedAt:receivedAt,status:i<2?"RESOLVED":"OPEN",resolvedAt:i<2?new Date(receivedAt.getTime()+2*day):null}});}
    }
    await prisma.auditEvent.create({data:{actorUserId:users[0].id,entityType:"PURCHASE_REQUISITION",entityId:req.id,action:"REQUISITION_CREATED",metadata:{seeded:true,requisitionNumber:req.requisitionNumber}}});
  }
  const ordersWithoutReceipt=await prisma.purchaseOrder.findMany({where:{receipts:{none:{}}},include:{lines:true},take:300,orderBy:{issuedAt:"asc"}});
  for(let i=0;i<ordersWithoutReceipt.length;i++){const po=ordersWithoutReceipt[i],partial=i%7===0,quantity=Number(po.lines[0].quantity),received=partial?Math.max(1,quantity-1):quantity,receivedAt=new Date(now.getTime()-(20-i%18)*day);const receipt=await prisma.receipt.create({data:{receiptNumber:"GR-2026-"+String(100+i).padStart(6,"0"),purchaseOrderId:po.id,facilityId:po.facilityId,receivedById:users[0].id,receivedAt,status:partial?"PARTIAL":"COMPLETE",notes:partial?"Consegna parziale, saldo atteso.":"Consegna verificata.",lines:{create:{purchaseOrderLineId:po.lines[0].id,quantityOrdered:quantity,quantityReceived:received,quantityAccepted:received,quantityRejected:0}}},include:{lines:true}});await prisma.purchaseOrder.update({where:{id:po.id},data:{status:partial?"PARTIALLY_RECEIVED":"RECEIVED"}});if(i<10){const openedAt=new Date(receivedAt.getTime()+2*60*60*1000);await prisma.qualityIssue.create({data:{receiptLineId:receipt.lines[0].id,purchaseOrderLineId:po.lines[0].id,issueType:issueTypes[i%issueTypes.length],severity:i%4===0?"HIGH":"MEDIUM",affectedQuantity:1,description:["Quantità inferiore al documento di trasporto.","Imballo esterno danneggiato.","Referenza consegnata non corrispondente.","Prestazione qualitativa da verificare.","Confezione non integra."][i%5],openedAt,status:i<4?"RESOLVED":i<7?"UNDER_REVIEW":"OPEN",resolutionType:i<4?"replacement":null,resolutionNote:i<4?"Sostituzione concordata con il fornitore.":null,resolvedAt:i<4?new Date(openedAt.getTime()+2*day):null}});}}
  await prisma.favorite.createMany({data:products.slice(0,12).map(p=>({userId:users[0].id,facilityId:facilities[0].id,canonicalProductId:p.id}))});
  const weekly=await prisma.shoppingList.create({data:{userId:users[0].id,facilityId:facilities[0].id,name:"Ordine settimanale igiene",description:"Scorta ricorrente per reparti e spazi comuni.",lastUsedAt:new Date(now.getTime()-7*day)}});await prisma.shoppingListItem.createMany({data:products.slice(0,6).map((p,i)=>({shoppingListId:weekly.id,canonicalProductId:p.id,quantity:4+i}))});
  const care=await prisma.shoppingList.create({data:{userId:users[0].id,facilityId:facilities[0].id,name:"Dotazione mensile assistenza",description:"Materiali ricorrenti per l’assistenza quotidiana.",lastUsedAt:new Date(now.getTime()-30*day)}});await prisma.shoppingListItem.createMany({data:products.slice(13,19).map((p,i)=>({shoppingListId:care.id,canonicalProductId:p.id,quantity:3+i}))});
  await prisma.auditEvent.createMany({data:[
    {actorUserId:users[0].id,entityType:"SHOPPING_LIST",entityId:weekly.id,action:"LIST_USED",metadata:{seeded:true},createdAt:new Date(now.getTime()-7*day)},
    {actorUserId:users[0].id,entityType:"PURCHASE_ORDER",entityId:"demo-received",action:"RECEIPT_CREATED",metadata:{seeded:true},createdAt:new Date(now.getTime()-5*day)},
    {actorUserId:users[0].id,entityType:"FAVORITE",entityId:products[0].id,action:"FAVORITE_ADDED",metadata:{seeded:true},createdAt:new Date(now.getTime()-3*day)},
    {actorUserId:users[0].id,entityType:"PURCHASE_REQUISITION",entityId:"demo-approved",action:"APPROVED",metadata:{seeded:true},createdAt:new Date(now.getTime()-2*day)},
    {actorUserId:users[0].id,entityType:"PURCHASE_ORDER",entityId:"demo-order",action:"PO_CREATED",metadata:{seeded:true},createdAt:new Date(now.getTime()-day)},
  ]});
  await prisma.approvalDelegation.create({data:{delegatorId:users[1].id,delegateId:users[2].id,organizationId:anteo.id,scopeType:"AREA",scopeId:areas[0].id,approvalLimit:15000,validFrom:new Date("2026-08-15"),validUntil:new Date("2026-09-15"),active:true}});
  await prisma.outOfCatalogRequest.createMany({data:[{requestNumber:"FC-2026-000001",requesterId:users[0].id,organizationId:anteo.id,facilityId:facilities[0].id,categoryId:categories[6].id,needDescription:"Ricambio specifico per sollevatore di reparto",quantity:2,estimatedAmount:480,suggestedSupplier:"Centro Ausili Italia",justification:"Ripristino urgente dell’attrezzatura di mobilizzazione",status:"UNDER_REVIEW"},{requestNumber:"FC-2026-000002",requesterId:users[0].id,organizationId:anteo.id,facilityId:facilities[0].id,categoryId:categories[3].id,needDescription:"Detergente dermatologico in formato professionale",quantity:12,estimatedAmount:210,justification:"Prodotto richiesto dal protocollo assistenziale interno",status:"SUBMITTED"}]});
  await seedSmartImports({prisma,organization:anteo,suppliers,uploader:users[2],products,offers,now,day});
  console.log(`Seed completo: ${facilities.length} strutture, ${products.length} prodotti, ${offers.length} offerte, ${requisitionCount} richieste, ${approvedCount} ordini.`);
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());
