import Link from "next/link";
import { DataTable, EmptyState, PageHeader, StatusChip } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatDate, formatMoney } from "@/lib/pricing";
import { statusLabel } from "@/lib/presentation/status";
import { approvalSla } from "@/lib/procurement/approval-sla";

export default async function ApprovalsPage({ searchParams }: { searchParams: Promise<{ decision?: string }> }) {
  const context = await requireRoles(["AREA_MANAGER", "PROCUREMENT_MANAGER"]);
  const approvals = await prisma.approvalRequest.findMany({ where: { approverUserId: context.user.id }, include: { requisition: { include: { facility: true, requester: true } } }, orderBy: { requestedAt: "desc" } });
  const actionable = approvals.filter(({ status }) => status === "PENDING").sort((a, b) => approvalSla(b.requestedAt).ageDays - approvalSla(a.requestedAt).ageDays || a.requestedAt.getTime() - b.requestedAt.getTime());
  const history = approvals.filter(({ status }) => status !== "PENDING");
  const decision = (await searchParams).decision;
  const table = (rows: typeof approvals, label: string, operational = false) => <><div className="approval-inbox-table"><DataTable label={label}><thead><tr><th>Richiesta</th><th>Struttura</th><th>Richiedente</th><th>Importo</th><th>Budget residuo</th><th>Motivo</th><th>Inviata</th><th>Attesa / SLA</th><th>Stato</th></tr></thead><tbody>{rows.map((approval) => { const sla = approvalSla(approval.requestedAt); return <tr key={approval.id}><td><Link className="table-link" href={`/approvals/${approval.id}`}>{approval.requisition.requisitionNumber}</Link></td><td>{approval.requisition.facility.name}</td><td>{approval.requisition.requester.name}</td><td>{formatMoney(Number(approval.requisition.total))}</td><td>{formatMoney(Number(approval.requisition.budgetAfter))}</td><td>{approval.reason}</td><td>{formatDate(approval.requestedAt)}</td><td>{sla.ageDays} gg · target {sla.targetDays}<StatusChip variant={sla.state === "overdue" ? "danger" : sla.state === "warn" ? "warn" : "ok"}>{sla.label}</StatusChip></td><td><StatusChip variant={approval.status === "PENDING" ? "warn" : approval.status === "APPROVED" ? "ok" : "neutral"}>{statusLabel(approval.status)}</StatusChip></td></tr>; })}</tbody></DataTable></div><div className="approval-inbox-cards" aria-label={label}>{rows.map((approval) => { const sla=approvalSla(approval.requestedAt); return <article key={approval.id}><header><div><span>{approval.requisition.facility.name}</span><h3>{approval.requisition.requisitionNumber}</h3></div><strong>{formatMoney(Number(approval.requisition.total))}</strong></header><p>{approval.reason}</p><dl><div><dt>Richiedente</dt><dd>{approval.requisition.requester.name}</dd></div><div><dt>Attesa</dt><dd>{sla.ageDays} gg · {sla.label}</dd></div><div><dt>Budget residuo</dt><dd>{formatMoney(Number(approval.requisition.budgetAfter))}</dd></div></dl><footer><StatusChip variant={operational ? "warn" : "neutral"}>{statusLabel(approval.status)}</StatusChip><Link className={operational ? "primary-cta" : "secondary-cta"} href={`/approvals/${approval.id}`}>{operational ? "Valuta richiesta" : "Apri dettaglio"}</Link></footer></article>; })}</div></>;
  return <main>{decision && <div className="success">Decisione registrata: {statusLabel(decision)}.</div>}<PageHeader eyebrow={context.roleCode === "AREA_MANAGER" ? "Governance di area" : "Eccezioni procurement"} title="Approvazioni" description="Priorità ordinate per anzianità e SLA." /><section><div className="section-heading"><div><h2>Da decidere · {actionable.length}</h2></div></div>{actionable.length ? table(actionable, "Richieste da decidere", true) : <EmptyState title="Nessuna decisione in sospeso" description="Non ci sono richieste assegnate al tuo perimetro." />}</section>{history.length > 0 && <details className="workspace-section"><summary>Archivio · {history.length} decisioni</summary>{table(history.slice(0, 30), "Storico approvazioni")}</details>}</main>;
}
