import Link from "next/link";
import { removeCartLine, saveCartAsList, submitRequisition, toggleFavorite, updateCartLine } from "@/app/buying-actions";
import { ProductImage } from "@/components/product-image";
import { EmptyState, PageHeader, PriceBlock, StatusChip, StickyActionBar } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatMoney } from "@/lib/pricing";
import { normalizeOfferPrice } from "@/lib/pricing/normalization";
import { getFacilityBudget } from "@/lib/procurement/budget";
import { evaluateCommercialConditions } from "@/lib/procurement/commercial-conditions";
import { evaluateFacilityProcurementLimits } from "@/lib/procurement/limits";
import { resolveScope } from "@/lib/scope";

export default async function CartPage() {
  const context = await requireRoles(["RSA_DIRECTOR"]);
  const scope = await resolveScope(context.assignment);
  const [cart, budget, favorites, recurring] = await Promise.all([
    prisma.cart.findUnique({ where: { userId_facilityId: { userId: context.user.id, facilityId: scope.id } }, include: { lines: { include: { canonicalProduct: { include: { category: true } }, supplierOffer: { include: { supplier: true } } } } } }),
    getFacilityBudget(scope.id),
    prisma.favorite.findMany({ where: { userId: context.user.id, facilityId: scope.id }, select: { canonicalProductId: true } }),
    prisma.shoppingList.findMany({ where: { userId: context.user.id, facilityId: scope.id }, include: { items: { include: { canonicalProduct: { include: { offers: { where: { active: true }, select: { supplierId: true, unitPrice: true } } } } } } }, orderBy: { updatedAt: "desc" }, take: 4 }),
  ]);
  if (!cart?.lines.length) return <main><PageHeader eyebrow="Acquisto guidato" title="Carrello" description="Qui troverai i prodotti prima di inviare la richiesta." /><EmptyState title="Il carrello è vuoto" description="Cerca nel catalogo, usa un preferito oppure aggiungi una lista ricorrente." action={<Link className="primary-cta" href="/catalog">Vai al catalogo</Link>} /></main>;
  const favoriteIds = new Set(favorites.map(({ canonicalProductId }) => canonicalProductId));
  const subtotal = cart.lines.reduce((sum, line) => sum + Number(line.quantity) * Number(line.supplierOffer.unitPrice), 0);
  const iva = cart.lines.reduce((sum, line) => sum + Number(line.quantity) * Number(line.supplierOffer.unitPrice) * Number(line.supplierOffer.taxRate) / 100, 0);
  const commercialGroups = Object.entries(Object.groupBy(cart.lines, (line) => line.supplierOffer.supplierId)).map(([supplierId, lines]) => { const supplier = lines![0].supplierOffer.supplier; const groupSubtotal = lines!.reduce((sum, line) => sum + Number(line.quantity) * Number(line.supplierOffer.unitPrice), 0); return { supplierId, supplier, lines: lines!, commercial: evaluateCommercialConditions(groupSubtotal, supplier) }; });
  const commercialCosts = commercialGroups.reduce((sum, group) => sum + group.commercial.shippingFee + group.commercial.surcharge, 0);
  const total = subtotal + iva + commercialCosts;
  const limits = await evaluateFacilityProcurementLimits(scope.id, cart.lines.map((line) => ({ canonicalProductId: line.canonicalProductId, categoryId: line.canonicalProduct.categoryId, productName: line.canonicalProduct.name, quantity: Number(line.quantity), unitPrice: Number(line.supplierOffer.unitPrice), unitsPerPackage: Number(line.canonicalProduct.unitsPerPackage ?? 1), consumptionUomLabel: line.canonicalProduct.consumptionUomLabel })));
  const limitGroups = [...new Map(limits.map((limit) => [`${limit.limitId}:${limit.productId}`, limit])).values()];
  const problematic = commercialGroups.filter(({ commercial }) => commercial.signals.some(({ severity }) => severity !== "info"));
  const autoApproved = total <= Number(context.assignment.approvalLimit) && total <= budget.available && !limits.some((limit) => limit.exceeded);
  return <main className="phase1-page phase1-cart">
    <PageHeader eyebrow="Acquisto guidato" title="Carrello" description={`${cart.lines.length} articoli · ${commercialGroups.length} fornitori · ${scope.label}`} />
    {problematic.length > 0 && <div className="phase1-commercial-alert"><div><strong>{problematic.length} {problematic.length === 1 ? "fornitore richiede" : "fornitori richiedono"} attenzione</strong><span>Valuta consolidamento, soglie d’ordine e costi prima dell’invio.</span></div><StatusChip variant={problematic.some(({ commercial }) => commercial.signals.some(({ severity }) => severity === "blocking")) ? "danger" : "warn"}>{commercialCosts ? `Extra ${formatMoney(commercialCosts)}` : "Soglie non raggiunte"}</StatusChip></div>}
    <div className="phase1-cart-layout"><div className="phase1-supplier-list">{commercialGroups.map(({ supplierId, supplier, lines, commercial }, groupIndex) => {
      const minProgress = commercial.minimum ? Math.min(100, commercial.subtotal / commercial.minimum * 100) : 100;
      const suggestion = recurring.flatMap((list) => list.items.map((item) => ({ list, item, offer: item.canonicalProduct.offers.find((offer) => offer.supplierId === supplierId) }))).filter(({ offer, item }) => offer && !lines.some((line) => line.canonicalProductId === item.canonicalProductId));
      const state = commercial.signals.some(({ severity }) => severity === "blocking") ? "danger" : commercial.signals.some(({ severity }) => severity === "warning") ? "warn" : "ok";
      return <details className={`phase1-supplier-group state-${state}`} key={supplierId} open={groupIndex === 0 || state === "danger"}>
        <summary><span className="supplier-disclosure" aria-hidden /><div><h2>{supplier.name}</h2><span>{lines.length} articoli · consegna indicativa {Math.max(...lines.map((line) => line.supplierOffer.leadTimeDays))} gg</span></div><div className="supplier-threshold"><strong>{formatMoney(commercial.totalCost)}</strong><span>{state === "ok" ? "Condizioni soddisfatte" : commercial.minimum && commercial.subtotal < commercial.minimum ? `Mancano ${formatMoney(commercial.minimum - commercial.subtotal)} al minimo` : `Mancano ${formatMoney(Math.max(0, (commercial.freeShipping ?? 0) - commercial.subtotal))} al franco porto`}</span><i><b style={{ width: `${minProgress}%` }} /></i></div><StatusChip variant={state}>{state === "ok" ? "OK" : state === "danger" ? "Bloccante" : "Attenzione"}</StatusChip></summary>
        <div className="phase1-threshold-detail"><span>Minimo {commercial.minimum ? formatMoney(commercial.minimum) : "non previsto"}</span><span>Franco porto {commercial.freeShipping ? formatMoney(commercial.freeShipping) : "non previsto"}</span><span>Spedizione/maggiorazione {formatMoney(commercial.shippingFee + commercial.surcharge)}</span></div>
        <div className="phase1-cart-lines">{lines.map((line) => { const normalized = normalizeOfferPrice(line.canonicalProduct, line.supplierOffer); return <article className="cart-line enriched" key={line.id}><ProductImage name={line.canonicalProduct.name} categoryCode={line.canonicalProduct.category.code} /><div><strong>{line.canonicalProduct.name}</strong><span>{line.canonicalProduct.category.name}</span><PriceBlock normalizedPrice={normalized.normalizedPrice} normalizedUom={line.canonicalProduct.consumptionUomLabel} packPrice={Number(line.supplierOffer.unitPrice)} packSize={line.canonicalProduct.packageDescription} variant="compact" /></div><form action={updateCartLine}><input type="hidden" name="lineId" value={line.id} /><input aria-label={`Quantità di ${line.canonicalProduct.name}`} name="quantity" type="number" min="1" defaultValue={Number(line.quantity)} /><button className="secondary-cta">Aggiorna</button></form><strong>{formatMoney(Number(line.quantity) * Number(line.supplierOffer.unitPrice))}</strong><div className="cart-line-actions"><form action={toggleFavorite}><input type="hidden" name="productId" value={line.canonicalProductId} /><button className="text-button">{favoriteIds.has(line.canonicalProductId) ? "Nei preferiti" : "Preferito"}</button></form><form action={removeCartLine}><input type="hidden" name="lineId" value={line.id} /><button className="text-button">Rimuovi</button></form></div></article>; })}</div>
        {suggestion.length > 0 && <aside className="phase1-completion"><div><strong>Completa con acquisti ricorrenti</strong><span>In {suggestion[0].list.name} ci sono {suggestion.length} prodotti dello stesso fornitore.</span></div><Link href={`/liste/${suggestion[0].list.id}`} className="secondary-cta">Valuta completamento</Link></aside>}
      </details>;
    })}</div>
      <aside className="phase1-checkout"><h2>Decisione d’acquisto</h2><dl><div><dt>Merci</dt><dd>{formatMoney(subtotal)}</dd></div><div><dt>Extra commerciali</dt><dd>{formatMoney(commercialCosts)}</dd></div><div><dt>IVA</dt><dd>{formatMoney(iva)}</dd></div><div className="total"><dt>Totale effettivo</dt><dd>{formatMoney(total)}</dd></div></dl><section><h3>Controlli applicabili</h3>{limitGroups.length ? limitGroups.slice(0, 3).map((limit) => <details className={`phase1-limit ${limit.exceeded ? "is-exceeded" : ""}`} key={`${limit.limitId}:${limit.productId}`}><summary><span title={limit.productName}>{limit.productName}</span><StatusChip variant={limit.exceeded ? "danger" : "ok"}>{limit.exceeded ? "Superato" : "OK"}</StatusChip></summary><dl><div><dt>Richiesto</dt><dd>{limit.requested.toLocaleString("it-IT")} {limit.uom}</dd></div><div><dt>Residuo dopo</dt><dd>{limit.remainingAfter.toLocaleString("it-IT")} {limit.uom}</dd></div></dl><small>{limit.scopeLabel} · {limit.periodLabel}</small></details>) : <p className="muted">Nessun limite prodotto specifico; resta attivo il budget generale.</p>}<div className="phase1-budget-row"><span>Budget struttura · periodo corrente</span><strong>{formatMoney(budget.available - total)}</strong><small>residuo dopo la richiesta</small></div></section><div className="policy-preview"><strong>{autoApproved ? "Approvazione automatica prevista" : "Richiede approvazione"}</strong><p>{autoApproved ? "Importo e limiti rientrano nell’autonomia." : "La richiesta sarà instradata con motivazione e dettaglio."}</p></div><form id="checkout-submit" action={submitRequisition} className="submit-form"><label>Motivazione<textarea name="justification" placeholder="Spiega il bisogno o l’eventuale eccezione" /></label><label>Consegna richiesta entro<input name="requiredByDate" type="date" /></label></form><details className="phase1-save-list"><summary>Salva come lista ricorrente</summary><form action={saveCartAsList}><input required minLength={3} name="name" placeholder="Nome lista" /><button className="secondary-cta">Salva lista</button></form></details></aside>
    </div>
    <StickyActionBar summary={<><strong>{formatMoney(total)}</strong><span>{commercialCosts ? `${formatMoney(commercialCosts)} di extra · ` : ""}{autoApproved ? "approvazione automatica" : "richiede approvazione"}</span></>}><button form="checkout-submit" className="primary-cta">Invia richiesta</button></StickyActionBar>
  </main>;
}
