import Link from "next/link";
import { ArrowIcon } from "@/components/icons";
import { Metric, PageHeader, ScopeBadge } from "@/components/ui";
import { getCurrentDemoUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { resolveScope } from "@/lib/scope";

export default async function Home() {
  const context = await getCurrentDemoUser();
  const scope = await resolveScope(context.assignment);
  if (context.roleCode === "EXECUTIVE_SPONSOR") return <main><PageHeader eyebrow="Executive" title="Control Tower" description="Open the executive view for current network indicators." /><Link className="primary-cta" href="/control-tower">Open Control Tower <ArrowIcon /></Link></main>;
  if (context.roleCode === "FINANCE_CONTROLLER") return <main><PageHeader eyebrow="Finance" title="Finance workspace" description={`Buongiorno, ${context.user.name.split(" ")[0]}. Your workspace for ${context.organization.name} is intentionally focused.`} /><section className="future-panel"><p className="eyebrow">Next capability</p><h2>Financial controls are on the roadmap</h2><p>Invoice matching and budget control will be activated in a subsequent milestone. No simulated finance operations are available yet.</p></section></main>;
  const [products, preferredSuppliers, suppliers, priceLists] = await Promise.all([prisma.canonicalProduct.count(), prisma.supplier.count({ where: { offers: { some: { preferred: true } } } }), prisma.supplier.count({ where: { active: true } }), prisma.priceList.count({ where: { active: true } })]);
  if (context.roleCode === "RSA_DIRECTOR") return <main><PageHeader eyebrow="Facility workspace" title={`Buongiorno, ${context.user.name.split(" ")[0]}`} description="Everything relevant to your facility, in one focused workspace." /><section className="context-panel"><div><span>Your facility</span><h2>{scope.facility}</h2><p>{scope.area} · {scope.organization}</p></div><ScopeBadge type={scope.type} label={scope.label} /></section><div className="metrics-grid"><Metric label="Catalog products available" value={products} detail="Current canonical catalog" /><Metric label="Preferred suppliers" value={preferredSuppliers} detail="Across active offers" /></div><Link href="/catalog" className="primary-cta">Vai al catalogo <ArrowIcon /></Link></main>;
  if (context.roleCode === "AREA_MANAGER") return <main><PageHeader eyebrow="Area overview" title={`Buongiorno, ${context.user.name.split(" ")[0]}`} description={`${scope.area} · ${scope.facilityIds.length} facilities in your scope`} /><section className="context-panel"><div><span>Your operational scope</span><h2>{scope.area}</h2><p>{scope.organization}</p></div><ScopeBadge type={scope.type} label={scope.label} /></section><div className="metrics-grid three"><Metric label="Facilities in scope" value={scope.facilityIds.length} /><Metric label="Catalog products" value={products} /><Metric label="Active suppliers" value={suppliers} /></div><div className="cta-row"><Link href="/facilities" className="primary-cta">View facilities <ArrowIcon /></Link><Link href="/catalog" className="secondary-cta">Browse catalog</Link></div></main>;
  const admin = context.roleCode === "PROCUREMENT_ADMIN";
  return <main><PageHeader eyebrow={admin ? "Platform administration" : "Joint procurement"} title={`Buongiorno, ${context.user.name.split(" ")[0]}`} description={admin ? "Organization, identity and procurement master data." : "A current view of products, suppliers and pricing coverage."} /><div className="metrics-grid four"><Metric label="Canonical products" value={products} /><Metric label="Active suppliers" value={suppliers} /><Metric label="Active price lists" value={priceLists} /><Metric label="Preferred suppliers" value={preferredSuppliers} /></div><section className="section-block"><h2>{admin ? "Administration workspace" : "Procurement workspace"}</h2><p>{admin ? "Review organization structure and role–scope assignments without changing source data." : "Review price coverage and identify comparable products across supplier lists."}</p><Link className="text-link" href={admin ? "/organization" : "/products"}>{admin ? "Open organization" : "Review products"} <ArrowIcon /></Link></section></main>;
}
