import Link from "next/link";
import { Prisma } from "@prisma/client";
import { manageSupplier } from "@/app/admin-actions";
import { AdminFeedback, AdminPanel } from "@/components/admin-crud";
import { DataTable, EmptyRow, PageHeader, Pagination, SearchField, StatusChip } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
const PAGE_SIZE=20;
export default async function SuppliersPage({searchParams}:{searchParams:Promise<{q?:string;stato?:string;pagina?:string;esito?:string}>}){
 const context=await requireRoles(["PROCUREMENT_MANAGER","PROCUREMENT_ADMIN"]),query=await searchParams,page=Math.max(1,Number(query.pagina??1)),admin=context.roleCode==="PROCUREMENT_ADMIN";
 const where:Prisma.SupplierWhereInput={...(query.q?{OR:[{name:{contains:query.q,mode:"insensitive"}},{vatNumber:{contains:query.q,mode:"insensitive"}}]}:{}),...(query.stato==="active"?{active:true}:query.stato==="inactive"?{active:false}:{})};
 const[total,rows]=await Promise.all([prisma.supplier.count({where}),prisma.supplier.findMany({where,include:{_count:{select:{offers:true,purchaseOrders:true}}},orderBy:{name:"asc"},skip:(page-1)*PAGE_SIZE,take:PAGE_SIZE})]),pages=Math.max(1,Math.ceil(total/PAGE_SIZE));
 return <main className="phase2-page phase2-list-page"><PageHeader eyebrow="Gestione fornitori" title="Fornitori" description={`${total} fornitori nel perimetro corrente`} action={admin?<AdminPanel label="Nuovo fornitore"><form action={manageSupplier} className="admin-crud-form"><input type="hidden" name="intent" value="create"/><label>Ragione sociale<input name="name" required minLength={3}/></label><label>Partita IVA<input name="vatNumber"/></label><label>Email<input name="contactEmail" type="email"/></label><button className="primary-cta">Crea fornitore</button></form></AdminPanel>:undefined}/><AdminFeedback result={query.esito}/><form className="phase2-control-bar"><SearchField defaultValue={query.q} placeholder="Fornitore o partita IVA"/><select name="stato" defaultValue={query.stato??"all"}><option value="all">Tutti</option><option value="active">Attivi</option><option value="inactive">Non attivi</option></select><button>Applica</button></form><DataTable label="Fornitori"><thead><tr><th>Fornitore</th><th>Contatto</th><th>Offerte</th><th>Ordini</th><th>Stato</th><th>{admin?"Gestione":"Apri"}</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td><Link className="table-link" href={`/suppliers/${row.id}`}>{row.name}</Link><small className="cell-detail">{row.vatNumber??"P.IVA non indicata"}</small></td><td>{row.contactEmail??"n.d."}</td><td className="num-cell">{row._count.offers}</td><td className="num-cell">{row._count.purchaseOrders}</td><td><StatusChip variant={row.active?"ok":"neutral"}>{row.active?"Attivo":"Non attivo"}</StatusChip></td><td>{admin?<details className="row-more"><summary>Modifica</summary><form action={manageSupplier} className="admin-crud-form"><input type="hidden" name="id" value={row.id}/><label>Ragione sociale<input name="name" defaultValue={row.name} required/></label><label>Partita IVA<input name="vatNumber" defaultValue={row.vatNumber??""}/></label><label>Email<input name="contactEmail" defaultValue={row.contactEmail??""} type="email"/></label><button name="intent" value="update">Salva</button>{row.active&&<button className="danger-secondary" name="intent" value="deactivate">Disattiva</button>}</form></details>:<Link href={`/suppliers/${row.id}`}>Apri</Link>}</td></tr>):<EmptyRow colSpan={6}>Nessun fornitore.</EmptyRow>}</tbody></DataTable><Pagination page={Math.min(page,pages)} pages={pages} pathname="/suppliers" params={{q:query.q,stato:query.stato}}/></main>;
}
