"use server";
import AdmZip from "adm-zip";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { start } from "workflow/api";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { assessEquivalence, confirmTechnicalAssociation, decideEquivalence, linkTechnicalDocument, processTechnicalBatch, stageTechnicalFile } from "@/lib/technical-intelligence/service";
import { supportedTechnicalExtensions, technicalExtension } from "@/lib/technical-intelligence/parser";
import { technicalBatchWorkflow } from "@/workflows/technical-batch";

const roles=["PROCUREMENT_MANAGER","PROCUREMENT_ADMIN"] as const;
type Pending={buffer:Buffer;filename:string;mimeType:string};
function redirectError(error:unknown){return error instanceof Error?error.message:"Operazione tecnica non riuscita.";}
async function bounded<T>(items:T[],limit:number,worker:(item:T)=>Promise<void>){let cursor=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length){const index=cursor++;await worker(items[index]);}}));}

export async function createTechnicalBatch(totalFiles:number,aiEnabled=true){const context=await requireRoles([...roles]);if(!Number.isInteger(totalFiles)||totalFiles<1||totalFiles>500)throw new Error("Un lotto deve contenere da 1 a 500 documenti.");return prisma.technicalDocumentBatch.create({data:{organizationId:context.organization.id,createdByUserId:context.user.id,status:"UPLOADED",totalFiles,aiEnabled},select:{id:true}});}

export async function stageTechnicalChunk(batchId:string,formData:FormData){
  const context=await requireRoles([...roles]),batch=await prisma.technicalDocumentBatch.findFirstOrThrow({where:{id:batchId,organizationId:context.organization.id,createdByUserId:context.user.id}}),files=formData.getAll("files").filter((item):item is File=>item instanceof File&&item.size>0);if(!files.length)throw new Error("Chunk vuoto.");
  const pending:Pending[]=[];for(const file of files){const buffer=Buffer.from(await file.arrayBuffer()),ext=technicalExtension(file.name);if(ext==="zip"){const zip=new AdmZip(buffer);for(const entry of zip.getEntries()){if(entry.isDirectory)continue;const name=entry.entryName.split(/[\\/]/).pop()??"";if(!supportedTechnicalExtensions.has(technicalExtension(name)))continue;pending.push({buffer:entry.getData(),filename:name,mimeType:"application/octet-stream"});}}else pending.push({buffer,filename:file.name,mimeType:file.type});}
  if(!pending.length)throw new Error("Nessun documento tecnico supportato nel chunk.");const existing=await prisma.technicalDocumentBatchItem.count({where:{batchId:batch.id}});if(existing+pending.length>500)throw new Error("Il lotto supera 500 documenti.");let duplicates=0;await bounded(pending,3,async file=>{const result=await stageTechnicalFile({...file,organizationId:context.organization.id,userId:context.user.id,batchId:batch.id});if(result.duplicate)duplicates++;});const expandedBy=pending.length-files.length;if(duplicates||expandedBy)await prisma.technicalDocumentBatch.update({where:{id:batch.id},data:{completedFiles:{increment:duplicates},totalFiles:{increment:expandedBy}}});return{staged:pending.length,duplicates};
}

export async function processTechnicalBatchAction(batchId:string){const context=await requireRoles([...roles]);const result=await processTechnicalBatch(batchId,context.organization.id,3);revalidatePath("/technical-documents");return{status:result.status,total:result.totalFiles,completed:result.completedFiles,failed:result.failedFiles,review:result.reviewRequiredFiles,queued:result.items.filter(item=>item.status==="QUEUED"||item.status==="PROCESSING").length,retryable:result.items.filter(item=>item.status==="FAILED").length};}
export async function startTechnicalBatch(batchId:string){const context=await requireRoles([...roles]);await prisma.technicalDocumentBatch.findFirstOrThrow({where:{id:batchId,organizationId:context.organization.id}});const run=await start(technicalBatchWorkflow,[batchId,context.organization.id]);await prisma.technicalDocumentBatch.update({where:{id:batchId},data:{status:"PROCESSING"}});return{runId:run.runId};}
export async function getTechnicalBatchProgress(batchId:string){const context=await requireRoles([...roles]);const batch=await prisma.technicalDocumentBatch.findFirstOrThrow({where:{id:batchId,organizationId:context.organization.id}});return{status:batch.status,total:batch.totalFiles,completed:batch.completedFiles,failed:batch.failedFiles,review:batch.reviewRequiredFiles};}

export async function decideTechnicalAssociation(formData:FormData){const context=await requireRoles([...roles]);try{await confirmTechnicalAssociation({associationId:String(formData.get("associationId")),organizationId:context.organization.id,userId:context.user.id,expectedVersion:Number(formData.get("version")),decision:String(formData.get("decision"))==="REJECT"?"REJECT":"CONFIRM"});}catch(error){redirect(`/technical-documents/${String(formData.get("documentId"))}?error=${encodeURIComponent(redirectError(error))}`);}revalidatePath("/technical-documents");redirect(`/technical-documents/${String(formData.get("documentId"))}?saved=1`);}
export async function associateTechnicalProduct(formData:FormData){const context=await requireRoles([...roles]);try{await linkTechnicalDocument({documentId:String(formData.get("documentId")),productId:String(formData.get("productId")),organizationId:context.organization.id,userId:context.user.id});}catch(error){redirect(`/technical-documents/${String(formData.get("documentId"))}?error=${encodeURIComponent(redirectError(error))}`);}revalidatePath("/technical-documents");redirect(`/technical-documents/${String(formData.get("documentId"))}?saved=1`);}
export async function runTechnicalComparison(formData:FormData){const context=await requireRoles([...roles]);const a=String(formData.get("productAId")),b=String(formData.get("productBId"));await assessEquivalence(context.organization.id,a,b);revalidatePath(`/technical-compare`);redirect(`/technical-compare?ids=${a},${b}&evaluated=1`);}
export async function decideTechnicalEquivalence(formData:FormData){const context=await requireRoles([...roles]),assessmentId=String(formData.get("assessmentId")),ids=String(formData.get("ids"));try{await decideEquivalence({assessmentId,organizationId:context.organization.id,userId:context.user.id,evidenceFingerprint:String(formData.get("evidenceFingerprint")),decision:formData.get("decision")==="REJECT"?"REJECT":"APPROVE",reason:String(formData.get("reason")??"")});}catch(error){redirect(`/technical-compare?ids=${ids}&error=${encodeURIComponent(redirectError(error))}`);}revalidatePath("/technical-compare");redirect(`/technical-compare?ids=${ids}&saved=1`);}
export async function createEvidenceRequirement(formData:FormData){const context=await requireRoles([...roles]),categoryId=String(formData.get("categoryId")),kind=String(formData.get("requirementType")),label=String(formData.get("label")??"").trim(),documentType=String(formData.get("documentType")??"")||null,attributeKey=String(formData.get("attributeKey")??"").trim()||null;if(label.length<3||!categoryId||!["DOCUMENT","ATTRIBUTE"].includes(kind)||kind==="DOCUMENT"&&!documentType||kind==="ATTRIBUTE"&&!attributeKey)throw new Error("Requisito tecnico incompleto.");await prisma.technicalEvidenceRequirement.create({data:{organizationId:context.organization.id,categoryId,requirementType:kind,label,documentType:documentType as never,attributeKey,equivalenceCritical:formData.get("equivalenceCritical")==="on",validityRequired:formData.get("validityRequired")==="on"}});revalidatePath("/technical-requirements");}
export async function setEvidenceRequirementActive(formData:FormData){const context=await requireRoles([...roles]),id=String(formData.get("id")),active=formData.get("active")==="true";const updated=await prisma.technicalEvidenceRequirement.updateMany({where:{id,organizationId:context.organization.id},data:{active}});if(!updated.count)throw new Error("Requisito non disponibile.");revalidatePath("/technical-requirements");}
