import { createHash, randomUUID } from "node:crypto";
import { Prisma, type TechnicalDocumentType } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { procurementAI } from "@/lib/procurement-ai";
import { getDocumentStorage, locatorForNewDocument, locatorFromSourceDocument, readSourceDocument } from "@/lib/storage";
import { buildTechnicalDocumentKey, sanitizeDocumentFilename } from "@/lib/storage/keys";
import { canonicalPair, compareTechnicalProfiles, deterministicTechnicalInterpretation, evidenceFingerprint, normalizeTechnicalKey, TECHNICAL_MATCH_THRESHOLDS, type TechnicalInterpretation } from "./engine";
import { extractTechnicalText, supportedTechnicalExtensions, technicalExtension } from "./parser";

export const MAX_TECHNICAL_FILE_BYTES=12*1024*1024;

function date(value?:string|null){if(!value)return null;const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed;}
function familyKey(data:TechnicalInterpretation){return normalizeTechnicalKey([data.manufacturer,data.brand,data.manufacturerSku??data.gtin,data.title,data.documentType].filter(Boolean).join("-"));}
function words(value:string){return new Set(normalizeTechnicalKey(value).split("_").filter(part=>part.length>2));}
function similarity(a:string,b:string){const aa=words(a),bb=words(b);if(!aa.size||!bb.size)return 0;const common=[...aa].filter(v=>bb.has(v)).length;return common/Math.max(aa.size,bb.size);}

export async function stageTechnicalFile(input:{buffer:Buffer;filename:string;mimeType:string;organizationId:string;userId:string;batchId:string}){
  if(!input.buffer.length)throw new Error("Il documento è vuoto.");if(input.buffer.length>MAX_TECHNICAL_FILE_BYTES)throw new Error("Il documento supera 12 MB.");
  const filename=sanitizeDocumentFilename(input.filename),ext=technicalExtension(filename);if(!supportedTechnicalExtensions.has(ext))throw new Error("Formato tecnico non supportato.");
  const checksum=createHash("sha256").update(input.buffer).digest("hex"),duplicate=await prisma.technicalDocumentVersion.findFirst({where:{technicalDocument:{organizationId:input.organizationId},checksum},select:{technicalDocumentId:true}});if(duplicate)return{queued:false,duplicate:true,documentId:duplicate.technicalDocumentId};
  const sourceId=randomUUID(),objectKey=buildTechnicalDocumentKey({organizationId:input.organizationId,sourceDocumentId:sourceId,checksum,filename}),locator=locatorForNewDocument(objectKey),storage=getDocumentStorage(locator.provider);
  await storage.put(locator,input.buffer,input.mimeType||"application/octet-stream");
  try{
    const item=await prisma.$transaction(async tx=>{
      const source=await tx.sourceDocument.create({data:{id:sourceId,organizationId:input.organizationId,uploadedByUserId:input.userId,originalFilename:filename,mimeType:input.mimeType||"application/octet-stream",fileSize:input.buffer.length,checksum,sourceType:ext.toUpperCase(),documentKind:"OTHER",storagePath:objectKey,storageProvider:locator.provider,storageBucket:locator.bucket,storageObjectKey:locator.objectKey,status:"UPLOADED",metadata:{technical:true,queued:true}}});
      return tx.technicalDocumentBatchItem.create({data:{batchId:input.batchId,sourceDocumentId:source.id}});
    });
    return{queued:true,duplicate:false,itemId:item.id};
  }catch(error){await storage.delete(locator).catch(()=>{});throw error;}
}

async function refreshBatchProgress(batchId:string){
  const [grouped,batch,retryable]=await Promise.all([prisma.technicalDocumentBatchItem.groupBy({by:["status"],where:{batchId},_count:{_all:true}}),prisma.technicalDocumentBatch.findUniqueOrThrow({where:{id:batchId}}),prisma.technicalDocumentBatchItem.count({where:{batchId,status:"FAILED",attempts:{lt:3}}})]),counts=Object.fromEntries(grouped.map(row=>[row.status,row._count._all])),itemCount=grouped.reduce((sum,row)=>sum+row._count._all,0),duplicateCount=Math.max(0,batch.totalFiles-itemCount);
  const completed=(counts.COMPLETED??0)+(counts.REVIEW_REQUIRED??0)+(counts.NEEDS_OCR??0)+duplicateCount,failed=counts.FAILED??0,terminal=completed+failed;
  await prisma.technicalDocumentBatch.update({where:{id:batchId},data:{completedFiles:completed,failedFiles:failed,reviewRequiredFiles:(counts.REVIEW_REQUIRED??0)+(counts.NEEDS_OCR??0),status:retryable||terminal<batch.totalFiles?"PROCESSING":failed===batch.totalFiles?"FAILED":failed?"PARTIAL":"COMPLETED"}});
}

export async function processTechnicalBatch(batchId:string,organizationId:string,limit=3){
  const now=new Date(),items=await prisma.technicalDocumentBatchItem.findMany({where:{batchId,batch:{organizationId},attempts:{lt:3},OR:[{status:"QUEUED"},{status:"FAILED"},{status:"PROCESSING",leaseExpiresAt:{lt:now}}]},orderBy:{createdAt:"asc"},take:Math.min(Math.max(limit,1),5),include:{sourceDocument:true,batch:{select:{aiEnabled:true}}}});
  await Promise.all(items.map(async item=>{
    const leaseToken=randomUUID(),claimed=await prisma.technicalDocumentBatchItem.updateMany({where:{id:item.id,OR:[{status:{in:["QUEUED","FAILED"]}},{status:"PROCESSING",leaseExpiresAt:{lt:now}}]},data:{status:"PROCESSING",leaseToken,leaseExpiresAt:new Date(Date.now()+120_000),attempts:{increment:1},startedAt:new Date(),lastError:null}});if(!claimed.count)return;
    try{
      const buffer=await readSourceDocument(item.sourceDocument),result=await ingestTechnicalFile({buffer,filename:item.sourceDocument.originalFilename,mimeType:item.sourceDocument.mimeType,organizationId,userId:item.sourceDocument.uploadedByUserId,batchId,sourceDocumentId:item.sourceDocumentId,aiEnabled:item.batch.aiEnabled});
      const document=await prisma.technicalDocument.findUnique({where:{id:result.documentId},select:{status:true}}),status=document?.status==="NEEDS_OCR"?"NEEDS_OCR":document?.status==="REVIEW_REQUIRED"?"REVIEW_REQUIRED":"COMPLETED";
      await prisma.technicalDocumentBatchItem.updateMany({where:{id:item.id,leaseToken},data:{technicalDocumentId:result.documentId,status,completedAt:new Date(),leaseToken:null,leaseExpiresAt:null}});
    }catch(error){const message=error instanceof Error?error.message.slice(0,500):"Elaborazione non riuscita";await prisma.technicalDocumentBatchItem.updateMany({where:{id:item.id,leaseToken},data:{status:"FAILED",lastError:message,leaseToken:null,leaseExpiresAt:null}});}
  }));
  await refreshBatchProgress(batchId);
  return prisma.technicalDocumentBatch.findFirstOrThrow({where:{id:batchId,organizationId},include:{items:{select:{status:true,attempts:true,maxAttempts:true}}}});
}

async function candidateProducts(organizationId:string,data:TechnicalInterpretation){
  const memory=await prisma.procurementMemory.findFirst({where:{organizationId,memoryType:"TECHNICAL_DOCUMENT_PRODUCT",lookupKey:familyKey(data)}});
  const remembered=memory&&typeof memory.canonicalValue==="object"&&memory.canonicalValue&&"canonicalProductIds" in memory.canonicalValue&&(memory.canonicalValue as {decision?:string}).decision!=="REJECT"?((memory.canonicalValue as {canonicalProductIds?:string[]}).canonicalProductIds??[]):[];
  const products=await prisma.canonicalProduct.findMany({where:{active:true,OR:[...(data.gtin?[{ean:data.gtin}]:[]),...(data.manufacturerSku?[{manufacturerSku:data.manufacturerSku}]:[]),...(remembered.length?[{id:{in:remembered}}]:[]),{name:{contains:data.title,mode:"insensitive"}}]},take:12});
  if(products.length)return products;
  const broad=await prisma.canonicalProduct.findMany({where:{active:true},take:500});return broad.map(product=>({product,score:similarity(data.title,product.name)})).filter(item=>item.score>=.3).sort((a,b)=>b.score-a.score).slice(0,8).map(item=>item.product);
}

function associationDecision(data:TechnicalInterpretation,product:{id:string;ean:string|null;manufacturerSku:string|null;name:string}){
  const evidence:string[]=[];let confidence=similarity(data.title,product.name),type="DESCRIPTION";
  if(data.gtin&&product.ean&&data.gtin===product.ean){confidence=1;type="GTIN_EXACT";evidence.push(`GTIN ${data.gtin}`);}
  else if(data.manufacturerSku&&product.manufacturerSku&&normalizeTechnicalKey(data.manufacturerSku)===normalizeTechnicalKey(product.manufacturerSku)){confidence=.99;type="MANUFACTURER_SKU_EXACT";evidence.push(`SKU produttore ${data.manufacturerSku}`);}
  else evidence.push(`Similarità descrizione ${(confidence*100).toFixed(0)}%`);
  const status=confidence>=TECHNICAL_MATCH_THRESHOLDS.deterministicAutoConfirm?"AUTO_CONFIRMED":confidence>=TECHNICAL_MATCH_THRESHOLDS.reviewRequired?"REVIEW_REQUIRED":"UNMATCHED";
  return {confidence,type,evidence,status} as const;
}

export async function ingestTechnicalFile(input:{buffer:Buffer;filename:string;mimeType:string;organizationId:string;userId:string;batchId:string;sourceDocumentId?:string;aiEnabled?:boolean}){
  if(!input.buffer.length)throw new Error("Il documento è vuoto.");if(input.buffer.length>MAX_TECHNICAL_FILE_BYTES)throw new Error("Il documento supera 12 MB.");
  const filename=sanitizeDocumentFilename(input.filename),ext=technicalExtension(filename);if(!supportedTechnicalExtensions.has(ext))throw new Error("Formato tecnico non supportato.");
  const checksum=createHash("sha256").update(input.buffer).digest("hex");
  const duplicate=await prisma.technicalDocumentVersion.findFirst({where:{technicalDocument:{organizationId:input.organizationId},checksum},select:{technicalDocumentId:true}});if(duplicate)return {documentId:duplicate.technicalDocumentId,duplicate:true};
  const existingSource=input.sourceDocumentId?await prisma.sourceDocument.findFirstOrThrow({where:{id:input.sourceDocumentId,organizationId:input.organizationId}}):null;
  const sourceId=existingSource?.id??randomUUID(),objectKey=existingSource?.storageObjectKey??buildTechnicalDocumentKey({organizationId:input.organizationId,sourceDocumentId:sourceId,checksum,filename}),locator=existingSource?locatorFromSourceDocument(existingSource):locatorForNewDocument(objectKey),storage=getDocumentStorage(locator.provider);
  if(!existingSource)await storage.put(locator,input.buffer,input.mimeType||"application/octet-stream");
  let sourceIdPersisted=Boolean(existingSource);
  try{
    const parsed=await extractTechnicalText(input.buffer,filename);
    const local=deterministicTechnicalInterpretation(filename,parsed.text);
    const ai=parsed.needsOcr||input.aiEnabled===false?null:procurementAI.isAi?await procurementAI.interpretTechnicalDocument(filename,parsed.text,{organizationId:input.organizationId,operation:"TECHNICAL_DOCUMENT"}):null;
    const interpretation=ai??local,key=familyKey(interpretation)||checksum;
    const result=await prisma.$transaction(async tx=>{
      const source=existingSource?await tx.sourceDocument.update({where:{id:sourceId},data:{status:parsed.needsOcr?"REQUIRES_PROVIDER":"PROCESSED",metadata:{technical:true,parserType:parsed.parserType}}}):await tx.sourceDocument.create({data:{id:sourceId,organizationId:input.organizationId,uploadedByUserId:input.userId,originalFilename:filename,mimeType:input.mimeType||"application/octet-stream",fileSize:input.buffer.length,checksum,sourceType:ext.toUpperCase(),documentKind:"OTHER",storagePath:objectKey,storageProvider:locator.provider,storageBucket:locator.bucket,storageObjectKey:locator.objectKey,status:parsed.needsOcr?"REQUIRES_PROVIDER":"PROCESSED",metadata:{technical:true,parserType:parsed.parserType}}});
      let document=await tx.technicalDocument.findUnique({where:{organizationId_familyKey:{organizationId:input.organizationId,familyKey:key}},include:{versions:true}});
      if(!document)document=await tx.technicalDocument.create({data:{organizationId:input.organizationId,batchId:input.batchId,familyKey:key,documentType:interpretation.documentType as TechnicalDocumentType,title:interpretation.title,manufacturer:interpretation.manufacturer,brand:interpretation.brand,language:interpretation.language,status:parsed.needsOcr?"NEEDS_OCR":"PROCESSING"},include:{versions:true}});
      const prior=document.versions.sort((a,b)=>b.versionNumber-a.versionNumber)[0],version=await tx.technicalDocumentVersion.create({data:{technicalDocumentId:document.id,sourceDocumentId:source.id,versionNumber:(prior?.versionNumber??0)+1,revision:interpretation.revision,revisionDate:date(interpretation.revisionDate),validFrom:date(interpretation.validFrom),validUntil:date(interpretation.validUntil),checksum,extractedMetadata:interpretation as Prisma.InputJsonValue,extractedTextHash:parsed.text?createHash("sha256").update(parsed.text).digest("hex"):null,interpretationProvider:ai?"OPENAI":"LOCAL_HEURISTIC",providerModel:ai?procurementAI.model:null,confidence:interpretation.confidence,status:parsed.needsOcr?"NEEDS_OCR":"READY"}});
      if(prior)await tx.technicalDocumentVersion.update({where:{id:prior.id},data:{status:"SUPERSEDED",supersededAt:new Date()}});
      await tx.technicalDocument.update({where:{id:document.id},data:{currentVersionId:version.id,documentType:interpretation.documentType as TechnicalDocumentType,title:interpretation.title,manufacturer:interpretation.manufacturer,brand:interpretation.brand,language:interpretation.language,status:parsed.needsOcr?"NEEDS_OCR":"READY"}});
      return {documentId:document.id,versionId:version.id,interpretation,needsOcr:parsed.needsOcr};
    },{timeout:30000});
    sourceIdPersisted=true;
    if(!result.needsOcr)await proposeAssociations(input.organizationId,result.documentId,result.versionId,result.interpretation,input.userId);
    return {...result,duplicate:false};
  }catch(error){if(!sourceIdPersisted)await storage.delete(locator).catch(()=>{});else await prisma.sourceDocument.update({where:{id:sourceId},data:{status:"FAILED"}}).catch(()=>{});throw error;}
}

async function proposeAssociations(organizationId:string,documentId:string,versionId:string,data:TechnicalInterpretation,userId:string){
  const candidates=await candidateProducts(organizationId,data);const confirmed:string[]=[];
  for(const product of candidates){const decision=associationDecision(data,product);if(decision.status==="UNMATCHED")continue;await prisma.technicalDocumentProductAssociation.upsert({where:{technicalDocumentId_canonicalProductId:{technicalDocumentId:documentId,canonicalProductId:product.id}},update:{confidence:decision.confidence,status:decision.status,evidence:decision.evidence,explanation:decision.evidence.join(" · "),associationType:decision.type,decisionSource:"DETERMINISTIC",version:{increment:1}},create:{technicalDocumentId:documentId,canonicalProductId:product.id,confidence:decision.confidence,status:decision.status,evidence:decision.evidence,explanation:decision.evidence.join(" · "),associationType:decision.type,decisionSource:"DETERMINISTIC"}});if(decision.status==="AUTO_CONFIRMED"){confirmed.push(product.id);await materializeAttributes(organizationId,product.id,versionId,data);await reassessProduct(organizationId,product.id);}}
  if(!candidates.length)await prisma.technicalDocument.update({where:{id:documentId},data:{status:"REVIEW_REQUIRED"}});
  else if(!confirmed.length)await prisma.technicalDocument.update({where:{id:documentId},data:{status:"REVIEW_REQUIRED"}});
  if(confirmed.length)await prisma.auditEvent.create({data:{actorUserId:userId,entityType:"TECHNICAL_DOCUMENT",entityId:documentId,action:"TECHNICAL_ASSOCIATION_AUTO_CONFIRMED",metadata:{productIds:confirmed}}});
}

async function materializeAttributes(organizationId:string,productId:string,versionId:string,data:TechnicalInterpretation){for(const attribute of data.technicalAttributes)await prisma.technicalProductAttribute.upsert({where:{canonicalProductId_technicalDocumentVersionId_attributeKey:{canonicalProductId:productId,technicalDocumentVersionId:versionId,attributeKey:normalizeTechnicalKey(attribute.key)}},update:{label:attribute.label,valueText:attribute.value,normalizedValue:attribute.normalizedValue,unit:attribute.unit,confidence:attribute.confidence,extractionSource:"DOCUMENT",reviewState:attribute.confidence>=TECHNICAL_MATCH_THRESHOLDS.attributeConfirmation?"CONFIRMED":"EXTRACTED"},create:{organizationId,canonicalProductId:productId,technicalDocumentVersionId:versionId,attributeKey:normalizeTechnicalKey(attribute.key),label:attribute.label,valueText:attribute.value,normalizedValue:attribute.normalizedValue,unit:attribute.unit,confidence:attribute.confidence,extractionSource:"DOCUMENT",reviewState:attribute.confidence>=TECHNICAL_MATCH_THRESHOLDS.attributeConfirmation?"CONFIRMED":"EXTRACTED"}});}
async function rememberAssociation(input:{organizationId:string;supplierId:string|null;lookupKey:string;productId:string;associationId:string;userId:string;decision?:"CONFIRM"|"REJECT"}){const existing=await prisma.procurementMemory.findFirst({where:{organizationId:input.organizationId,supplierId:input.supplierId,memoryType:"TECHNICAL_DOCUMENT_PRODUCT",lookupKey:input.lookupKey}}),data={canonicalValue:{canonicalProductIds:[input.productId],decision:input.decision??"CONFIRM"},sourceEntityId:input.associationId,confirmedByUserId:input.userId};if(existing)await prisma.procurementMemory.update({where:{id:existing.id},data});else await prisma.procurementMemory.create({data:{organizationId:input.organizationId,supplierId:input.supplierId,memoryType:"TECHNICAL_DOCUMENT_PRODUCT",lookupKey:input.lookupKey,...data}});}

export async function confirmTechnicalAssociation(input:{associationId:string;organizationId:string;userId:string;expectedVersion:number;decision:"CONFIRM"|"REJECT"}){
  const association=await prisma.technicalDocumentProductAssociation.findFirstOrThrow({where:{id:input.associationId,technicalDocument:{organizationId:input.organizationId}},include:{technicalDocument:{include:{currentVersion:true}},canonicalProduct:true}});
  const status=input.decision==="CONFIRM"?"MANUALLY_CONFIRMED":"REJECTED";const updated=await prisma.technicalDocumentProductAssociation.updateMany({where:{id:association.id,version:input.expectedVersion,status:{in:["REVIEW_REQUIRED","UNMATCHED"]}},data:{status,version:{increment:1},confirmedByUserId:input.decision==="CONFIRM"?input.userId:null,confirmedAt:input.decision==="CONFIRM"?new Date():null,rejectedAt:input.decision==="REJECT"?new Date():null,decisionSource:"HUMAN"}});if(!updated.count)throw new Error("La proposta è già stata aggiornata. Ricarica la pagina.");
  if(input.decision==="CONFIRM"&&association.technicalDocument.currentVersion){const data=association.technicalDocument.currentVersion.extractedMetadata as unknown as TechnicalInterpretation;await materializeAttributes(input.organizationId,association.canonicalProductId,association.technicalDocument.currentVersion.id,data);await rememberAssociation({organizationId:input.organizationId,supplierId:association.technicalDocument.supplierId,lookupKey:association.technicalDocument.familyKey,productId:association.canonicalProductId,associationId:association.id,userId:input.userId});await reassessProduct(input.organizationId,association.canonicalProductId);}
  if(input.decision==="REJECT")await rememberAssociation({organizationId:input.organizationId,supplierId:association.technicalDocument.supplierId,lookupKey:association.technicalDocument.familyKey,productId:association.canonicalProductId,associationId:association.id,userId:input.userId,decision:"REJECT"});
}

export async function linkTechnicalDocument(input:{documentId:string;productId:string;organizationId:string;userId:string}){
  const [document,product]=await Promise.all([prisma.technicalDocument.findFirstOrThrow({where:{id:input.documentId,organizationId:input.organizationId},include:{currentVersion:true}}),prisma.canonicalProduct.findFirstOrThrow({where:{id:input.productId,active:true}})]);if(!document.currentVersion)throw new Error("Il documento non ha una versione elaborata.");
  const association=await prisma.technicalDocumentProductAssociation.upsert({where:{technicalDocumentId_canonicalProductId:{technicalDocumentId:document.id,canonicalProductId:product.id}},update:{status:"MANUALLY_CONFIRMED",confidence:1,associationType:"MANUAL",evidence:["Selezione operatore"],explanation:"Associazione confermata dall'operatore",decisionSource:"HUMAN",confirmedByUserId:input.userId,confirmedAt:new Date(),rejectedAt:null,version:{increment:1}},create:{technicalDocumentId:document.id,canonicalProductId:product.id,status:"MANUALLY_CONFIRMED",confidence:1,associationType:"MANUAL",evidence:["Selezione operatore"],explanation:"Associazione confermata dall'operatore",decisionSource:"HUMAN",confirmedByUserId:input.userId,confirmedAt:new Date()}});
  await materializeAttributes(input.organizationId,product.id,document.currentVersion.id,document.currentVersion.extractedMetadata as unknown as TechnicalInterpretation);await reassessProduct(input.organizationId,product.id);await rememberAssociation({organizationId:input.organizationId,supplierId:document.supplierId,lookupKey:document.familyKey,productId:product.id,associationId:association.id,userId:input.userId});return association;
}

export async function reassessProduct(organizationId:string,productId:string){
  const product=await prisma.canonicalProduct.findFirstOrThrow({where:{id:productId,active:true},include:{category:true}}),now=new Date();
  const [requirements,associations,attributes]=await Promise.all([prisma.technicalEvidenceRequirement.findMany({where:{organizationId,categoryId:product.categoryId,active:true,required:true}}),prisma.technicalDocumentProductAssociation.findMany({where:{canonicalProductId:productId,status:{in:["AUTO_CONFIRMED","MANUALLY_CONFIRMED"]},technicalDocument:{organizationId}},include:{technicalDocument:{include:{currentVersion:true}}}}),prisma.technicalProductAttribute.findMany({where:{organizationId,canonicalProductId:productId,reviewState:{in:["EXTRACTED","CONFIRMED","CONFLICTED"]},technicalDocumentVersion:{status:"READY"}}})]);
  const missing=requirements.filter(req=>req.documentType?!associations.some(a=>a.technicalDocument.documentType===req.documentType):req.attributeKey?!attributes.some(a=>a.attributeKey===req.attributeKey):false),expired=associations.filter(a=>a.technicalDocument.currentVersion?.validUntil&&a.technicalDocument.currentVersion.validUntil<now),groups=Object.groupBy(attributes.filter(a=>a.reviewState!=="REJECTED"),a=>a.attributeKey),conflicts=Object.values(groups).filter(group=>new Set(group?.map(a=>`${a.valueText}|${a.unit??""}`)).size>1);
  await prisma.missingEvidenceItem.deleteMany({where:{organizationId,canonicalProductId:productId,assessmentId:null}});for(const req of missing)await prisma.missingEvidenceItem.create({data:{organizationId,canonicalProductId:productId,requirementId:req.id,requiredField:req.attributeKey,requiredDocumentType:req.documentType,reason:`Requisito ${req.label} non soddisfatto`,suggestedEvidence:req.documentType?`Carica ${req.documentType}`:`Documento con ${req.label}`}});
  const pending=await prisma.technicalDocumentProductAssociation.count({where:{canonicalProductId:productId,status:"REVIEW_REQUIRED",technicalDocument:{organizationId}}});
  const status=pending?"PENDING_REVIEW":conflicts.length?"CONFLICTED":expired.length?"EXPIRED_EVIDENCE":missing.length?"MISSING_EVIDENCE":requirements.length?"COMPLETE":"INCOMPLETE";
  const percent=requirements.length?Math.round((requirements.length-missing.length)/requirements.length*100):0,fingerprint=evidenceFingerprint({requirements:requirements.map(r=>r.id),associations:associations.map(a=>a.id),attributes:attributes.map(a=>[a.attributeKey,a.valueText,a.updatedAt])});
  const state=await prisma.productTechnicalState.upsert({where:{organizationId_canonicalProductId:{organizationId,canonicalProductId:productId}},update:{status,completenessPercent:percent,missingCount:missing.length,conflictCount:conflicts.length,expiredCount:expired.length,evaluatedAt:new Date(),evidenceFingerprint:fingerprint},create:{organizationId,canonicalProductId:productId,status,completenessPercent:percent,missingCount:missing.length,conflictCount:conflicts.length,expiredCount:expired.length,evidenceFingerprint:fingerprint}});
  const related=await prisma.productEquivalenceAssessment.findMany({where:{organizationId,OR:[{productAId:productId},{productBId:productId}]},select:{productAId:true,productBId:true}});
  for(const item of related)await assessEquivalence(organizationId,item.productAId,item.productBId);
  await refreshExactProductSavings(organizationId,productId);
  return state;
}

export async function assessEquivalence(organizationId:string,productAId:string,productBId:string){
  const [a,b]=canonicalPair(productAId,productBId),products=await prisma.canonicalProduct.findMany({where:{id:{in:[a,b]},active:true},include:{category:true}});if(products.length!==2)throw new Error("Prodotto non disponibile.");
  const exact=products[0].ean&&products[0].ean===products[1].ean||products[0].manufacturerSku&&products[0].manufacturerSku===products[1].manufacturerSku;
  const attrs=await prisma.technicalProductAttribute.findMany({where:{organizationId,canonicalProductId:{in:[a,b]},reviewState:{in:["CONFIRMED","EXTRACTED"]},technicalDocumentVersion:{status:"READY"}}}),profiles=Object.fromEntries([a,b].map(id=>[id,Object.fromEntries(attrs.filter(x=>x.canonicalProductId===id).map(x=>[x.attributeKey,`${x.valueText} ${x.unit??""}`.trim()]))])),requirements=await prisma.technicalEvidenceRequirement.findMany({where:{organizationId,categoryId:products[0].categoryId,active:true,equivalenceCritical:true,attributeKey:{not:null}}}),critical=requirements.map(r=>r.attributeKey!),comparison=exact?{result:"IDENTICAL" as const,confidence:1,matched:["deterministic_identifier"],differing:[],blocking:[],missing:[]}:products[0].categoryId!==products[1].categoryId?{result:"NOT_EQUIVALENT" as const,confidence:1,matched:[],differing:["category"],blocking:["category"],missing:[]}:compareTechnicalProfiles(profiles[a],profiles[b],critical),fingerprint=evidenceFingerprint({profiles,critical});
  const existing=await prisma.productEquivalenceAssessment.findUnique({where:{organizationId_productAId_productBId:{organizationId,productAId:a,productBId:b}}}),humanCurrent=existing?.decisionFingerprint===fingerprint&&(existing.reviewStatus==="HUMAN_APPROVED"||existing.reviewStatus==="HUMAN_REJECTED"),reviewStatus=humanCurrent?existing.reviewStatus:existing&&existing.evidenceFingerprint!==fingerprint?"STALE":comparison.result==="FUNCTIONALLY_EQUIVALENT"?"REVIEW_REQUIRED":"AI_PROPOSED";
  const assessment=await prisma.productEquivalenceAssessment.upsert({where:{organizationId_productAId_productBId:{organizationId,productAId:a,productBId:b}},update:{result:comparison.result,confidence:comparison.confidence,matchedCriteria:comparison.matched,differingCriteria:comparison.differing,blockingDifferences:comparison.blocking,evidenceSources:attrs.map(x=>x.technicalDocumentVersionId),explanation:comparison.result==="INSUFFICIENT_EVIDENCE"?`Evidenza mancante: ${comparison.missing.join(", ")}`:comparison.result==="NOT_EQUIVALENT"?`Differenze bloccanti: ${comparison.blocking.join(", ")}`:"Criteri tecnici compatibili",decisionSource:exact?"DETERMINISTIC_IDENTIFIER":"TECHNICAL_RULES",evidenceFingerprint:fingerprint,reviewStatus,...(!humanCurrent?{decisionReason:null,decisionFingerprint:null,reviewedByUserId:null,reviewedAt:null}:{})},create:{organizationId,productAId:a,productBId:b,result:comparison.result,confidence:comparison.confidence,matchedCriteria:comparison.matched,differingCriteria:comparison.differing,blockingDifferences:comparison.blocking,evidenceSources:attrs.map(x=>x.technicalDocumentVersionId),explanation:comparison.result==="INSUFFICIENT_EVIDENCE"?`Evidenza mancante: ${comparison.missing.join(", ")}`:comparison.result==="NOT_EQUIVALENT"?`Differenze bloccanti: ${comparison.blocking.join(", ")}`:"Criteri tecnici compatibili",decisionSource:exact?"DETERMINISTIC_IDENTIFIER":"TECHNICAL_RULES",evidenceFingerprint:fingerprint,reviewStatus}});
  await prisma.missingEvidenceItem.deleteMany({where:{assessmentId:assessment.id}});for(const key of comparison.missing)await prisma.missingEvidenceItem.create({data:{organizationId,canonicalProductId:a,comparedProductId:b,assessmentId:assessment.id,requiredField:key,reason:`${key} è necessario per stabilire l'equivalenza`,suggestedEvidence:`Scheda tecnica con ${key}`}});await refreshAssessmentSaving(assessment.id);return assessment;
}

export async function decideEquivalence(input:{assessmentId:string;organizationId:string;userId:string;evidenceFingerprint:string;decision:"APPROVE"|"REJECT";reason:string}){
  if(input.reason.trim().length<5)throw new Error("Inserisci una motivazione di almeno 5 caratteri.");
  const assessment=await prisma.productEquivalenceAssessment.findFirstOrThrow({where:{id:input.assessmentId,organizationId:input.organizationId}});if(assessment.evidenceFingerprint!==input.evidenceFingerprint)throw new Error("Le evidenze sono cambiate: rivaluta prima di decidere.");if(assessment.result!=="FUNCTIONALLY_EQUIVALENT")throw new Error("Solo una proposta di equivalenza funzionale può essere approvata o respinta.");
  const updated=await prisma.productEquivalenceAssessment.updateMany({where:{id:assessment.id,evidenceFingerprint:input.evidenceFingerprint,reviewStatus:{in:["AI_PROPOSED","REVIEW_REQUIRED","STALE"]}},data:{reviewStatus:input.decision==="APPROVE"?"HUMAN_APPROVED":"HUMAN_REJECTED",decisionReason:input.reason.trim(),decisionFingerprint:input.evidenceFingerprint,reviewedByUserId:input.userId,reviewedAt:new Date()}});if(!updated.count)throw new Error("La valutazione è già stata decisa o aggiornata.");
  await rememberEquivalence({...input,productAId:assessment.productAId,productBId:assessment.productBId});await refreshAssessmentSaving(assessment.id);return prisma.productEquivalenceAssessment.findUniqueOrThrow({where:{id:assessment.id}});
}

async function rememberEquivalence(input:{organizationId:string;userId:string;assessmentId:string;productAId:string;productBId:string;decision:"APPROVE"|"REJECT";evidenceFingerprint:string;reason:string}){const lookupKey=canonicalPair(input.productAId,input.productBId).join(":"),existing=await prisma.procurementMemory.findFirst({where:{organizationId:input.organizationId,memoryType:"TECHNICAL_EQUIVALENCE",lookupKey}}),data={canonicalValue:{decision:input.decision,evidenceFingerprint:input.evidenceFingerprint,reason:input.reason},sourceEntityId:input.assessmentId,confirmedByUserId:input.userId};if(existing)await prisma.procurementMemory.update({where:{id:existing.id},data});else await prisma.procurementMemory.create({data:{organizationId:input.organizationId,memoryType:"TECHNICAL_EQUIVALENCE",lookupKey,...data}});}

export async function refreshAssessmentSaving(assessmentId:string){
  const assessment=await prisma.productEquivalenceAssessment.findUniqueOrThrow({where:{id:assessmentId}}),eligible=assessment.result==="IDENTICAL"||assessment.result==="FUNCTIONALLY_EQUIVALENT"&&assessment.reviewStatus==="HUMAN_APPROVED",offers=await prisma.supplierOffer.findMany({where:{canonicalProductId:{in:[assessment.productAId,assessment.productBId]},active:true,normalizedUnitPrice:{not:null},supplier:{active:true},OR:[{validUntil:null},{validUntil:{gte:new Date()}}]},select:{id:true,canonicalProductId:true,normalizedUnitPrice:true,supplierId:true,priceListId:true}}),baseline=offers.filter(o=>o.canonicalProductId===assessment.productAId).sort((x,y)=>Number(x.normalizedUnitPrice)-Number(y.normalizedUnitPrice))[0],candidate=offers.filter(o=>o.canonicalProductId===assessment.productBId).sort((x,y)=>Number(x.normalizedUnitPrice)-Number(y.normalizedUnitPrice))[0],type=eligible?(assessment.result==="IDENTICAL"?"EXACT_PRODUCT_SAVING":"EQUIVALENT_PRODUCT_SAVING"):"INSUFFICIENT_TECHNICAL_EVIDENCE",fingerprint=evidenceFingerprint({assessment:assessment.evidenceFingerprint,baseline:baseline?.id,candidate:candidate?.id,type});
  const baselinePrice=baseline?Number(baseline.normalizedUnitPrice):null,candidatePrice=candidate?Number(candidate.normalizedUnitPrice):null,savingAmount=eligible&&baselinePrice!==null&&candidatePrice!==null?Math.max(0,baselinePrice-candidatePrice):null,savingPercent=savingAmount!==null&&baselinePrice?100*savingAmount/baselinePrice:null;
  return prisma.technicalSavingOpportunity.upsert({where:{organizationId_fingerprint:{organizationId:assessment.organizationId,fingerprint}},update:{baselinePrice,candidatePrice,savingAmount,savingPercent,evidenceComplete:eligible,confidence:assessment.confidence,status:eligible?"OPEN":"REVIEW_REQUIRED",reason:eligible?"Confronto basato su prezzo normalizzato ed evidenza tecnica approvata":"Nessuna sostituzione raccomandata senza evidenza tecnica approvata",provenance:{assessmentId:assessment.id,evidenceFingerprint:assessment.evidenceFingerprint}},create:{organizationId:assessment.organizationId,type,currentProductId:assessment.productAId,candidateProductId:assessment.productBId,currentOfferId:baseline?.id,candidateOfferId:candidate?.id,assessmentId:assessment.id,baselinePrice,candidatePrice,savingAmount,savingPercent,evidenceComplete:eligible,confidence:assessment.confidence,status:eligible?"OPEN":"REVIEW_REQUIRED",reason:eligible?"Confronto basato su prezzo normalizzato ed evidenza tecnica approvata":"Nessuna sostituzione raccomandata senza evidenza tecnica approvata",provenance:{assessmentId:assessment.id,evidenceFingerprint:assessment.evidenceFingerprint},fingerprint}});
}

export async function refreshExactProductSavings(organizationId:string,productId:string){
  const offers=await prisma.supplierOffer.findMany({where:{canonicalProductId:productId,active:true,normalizedUnitPrice:{not:null},supplier:{active:true},OR:[{validUntil:null},{validUntil:{gte:new Date()}}]},orderBy:[{preferred:"desc"},{normalizedUnitPrice:"asc"}],select:{id:true,supplierId:true,normalizedUnitPrice:true,priceListId:true,preferred:true}});if(offers.length<2)return null;
  const baseline=offers.find(offer=>offer.preferred)??offers[offers.length-1],candidate=offers.filter(offer=>offer.supplierId!==baseline.supplierId).sort((a,b)=>Number(a.normalizedUnitPrice)-Number(b.normalizedUnitPrice))[0];if(!candidate)return null;
  const baselinePrice=Number(baseline.normalizedUnitPrice),candidatePrice=Number(candidate.normalizedUnitPrice),savingAmount=Math.max(0,baselinePrice-candidatePrice),savingPercent=baselinePrice?100*savingAmount/baselinePrice:0,fingerprint=evidenceFingerprint({type:"EXACT_PRODUCT_SAVING",productId,baseline:baseline.id,candidate:candidate.id});
  return prisma.technicalSavingOpportunity.upsert({where:{organizationId_fingerprint:{organizationId,fingerprint}},update:{baselinePrice,candidatePrice,savingAmount,savingPercent,evidenceComplete:true,confidence:1,status:"OPEN",reason:"Stesso prodotto canonico, confronto tra prezzi normalizzati",provenance:{baselineOfferId:baseline.id,candidateOfferId:candidate.id}},create:{organizationId,type:"EXACT_PRODUCT_SAVING",currentProductId:productId,candidateProductId:productId,currentOfferId:baseline.id,candidateOfferId:candidate.id,baselinePrice,candidatePrice,savingAmount,savingPercent,evidenceComplete:true,confidence:1,status:"OPEN",reason:"Stesso prodotto canonico, confronto tra prezzi normalizzati",provenance:{baselineOfferId:baseline.id,candidateOfferId:candidate.id},fingerprint}});
}
