import { DataTable, EmptyState, PageHeader, ProductLink, SearchField } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { compareOffers, formatMoney, getComparablePrice } from "@/lib/pricing";
import { prisma } from "@/lib/prisma";

type Props = { searchParams: Promise<{ q?: string; category?: string; supplier?: string; sort?: string }> };
export default async function ProductsPage({ searchParams }: Props) {
  await requireRoles(["PROCUREMENT_MANAGER", "PROCUREMENT_ADMIN"]); const filters = await searchParams;
  const [categories, suppliers, products] = await Promise.all([prisma.category.findMany({ orderBy: { name: "asc" } }), prisma.supplier.findMany({ orderBy: { name: "asc" } }), prisma.canonicalProduct.findMany({ where: { AND: [filters.q ? { OR: [{ name: { contains: filters.q, mode: "insensitive" } }, { brand: { contains: filters.q, mode: "insensitive" } }] } : {}, filters.category ? { categoryId: filters.category } : {}, filters.supplier ? { offers: { some: { supplierId: filters.supplier } } } : {}] }, include: { category: true, offers: { include: { supplier: true } } } })]);
  const rows = products.map((product) => ({ product, comparison: compareOffers(product.offers) })).sort((a, b) => filters.sort === "spread" ? b.comparison.spread - a.comparison.spread : a.product.name.localeCompare(b.product.name));
  return <main><PageHeader eyebrow="Procurement master data" title="Products" description="Coverage, preferred sourcing and observed price dispersion by canonical product." /><form className="filter-bar"><SearchField defaultValue={filters.q} placeholder="Search products" /><select name="category" defaultValue={filters.category ?? ""}><option value="">All categories</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="supplier" defaultValue={filters.supplier ?? ""}><option value="">All suppliers</option>{suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="sort" defaultValue={filters.sort ?? "name"}><option value="name">Sort by name</option><option value="spread">Highest spread</option></select><button>Apply</button></form>{rows.length ? <DataTable label="Products"><thead><tr><th>Product</th><th>Category</th><th>Offers</th><th>Lowest price</th><th>Preferred supplier</th><th>Price spread</th></tr></thead><tbody>{rows.map(({ product, comparison }) => <tr key={product.id}><td><ProductLink id={product.id} name={product.name} detail={product.brand ?? undefined} /></td><td>{product.category.name}</td><td>{product.offers.length}</td><td>{comparison.lowest ? formatMoney(getComparablePrice(comparison.lowest), 4) : "—"}</td><td>{comparison.preferred?.supplier.name ?? "—"}</td><td><strong>{comparison.spread.toFixed(1)}%</strong></td></tr>)}</tbody></DataTable> : <EmptyState title="No products found" description="Try a broader filter combination." />}</main>;
}
