import { Prisma } from "@prisma/client";
import { manageProduct } from "@/app/admin-actions";
import { AdminFeedback, AdminPanel } from "@/components/admin-crud";
import { DataTable, EmptyRow, Num, PageHeader, Pagination, ProductLink, SearchField, StatusChip } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { compareOffers, getComparablePrice } from "@/lib/pricing";
const PAGE_SIZE=20;
export default async function ProductsPage({searchParams}:{searchParams:Promise<{q?:string;category?:string;pagina?:string;esito?:string}>}){
 const context=await requireRoles(["PROCUREMENT_MANAGER","PROCUREMENT_ADMIN"]),query=await searchParams,page=Math.max(1,Number(query.pagina??1)),admin=context.roleCode==="PROCUREMENT_ADMIN";
 const where:Prisma.CanonicalProductWhereInput={...(query.q?{name:{contains:query.q,mode:"insensitive"}}:{}),...(query.category?{categoryId:query.category}:{})};
 const[categories,total,rows]=await Promise.all([prisma.category.findMany({orderBy:{name:"asc"}}),prisma.canonicalProduct.count({where}),prisma.canonicalProduct.findMany({where,include:{category:true,offers:{where:{active:true},include:{supplier:true}}},orderBy:{name:"asc"},skip:(page-1)*PAGE_SIZE,take:PAGE_SIZE})]),pages=Math.max(1,Math.ceil(total/PAGE_SIZE));
 const fields=(row?:typeof rows[number])=><><label>Nome<input name="name" defaultValue={row?.name} required minLength={3}/></label><label>Categoria<select name="categoryId" defaultValue={row?.categoryId}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Unita acquisto<select name="uom" defaultValue={row?.purchaseUom??"PACK"}><option value="PACK">Confezione</option><option value="PIECE">Pezzo</option><option value="KG">Kg</option><option value="L">Litro</option></select></label></>;
 return <main className="phase2-page phase2-list-page"><PageHeader eyebrow="Anagrafica procurement" title="Prodotti" description={`${total} prodotti nel perimetro`} action={admin?<AdminPanel label="Nuovo prodotto"><form action={manageProduct} className="admin-crud-form"><input type="hidden" name="intent" value="create"/>{fields()}<button className="primary-cta">Crea prodotto</button></form></AdminPanel>:undefined}/><AdminFeedback result={query.esito}/><form className="phase2-control-bar"><SearchField defaultValue={query.q} placeholder="Nome prodotto"/><select name="category" defaultValue={query.category??""}><option value="">Tutte le categorie</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button>Applica</button></form><DataTable label="Prodotti"><thead><tr><th>Prodotto</th><th>Categoria</th><th>Offerte</th><th>Prezzo normalizzato</th><th>Stato</th>{admin&&<th>Gestione</th>}</tr></thead><tbody>{rows.length?rows.map(row=>{const comparison=compareOffers(row.offers);return <tr key={row.id}><td><ProductLink id={row.id} name={row.name} detail={row.brand??"Marca non indicata"}/></td><td>{row.category.name}</td><td className="num-cell">{row.offers.length}</td><td className="num-cell">{comparison.lowest?<Num value={getComparablePrice(comparison.lowest)} kind="currency" digits={4}/>:"-"}</td><td><StatusChip variant={row.active?"ok":"neutral"}>{row.active?"Attivo":"Non attivo"}</StatusChip></td>{admin&&<td><details className="row-more"><summary>Modifica</summary><form action={manageProduct} className="admin-crud-form"><input type="hidden" name="id" value={row.id}/>{fields(row)}<button name="intent" value="update">Salva</button>{row.active&&<button className="danger-secondary" name="intent" value="deactivate">Disattiva</button>}</form></details></td>}</tr>}):<EmptyRow colSpan={admin?6:5}>Nessun prodotto.</EmptyRow>}</tbody></DataTable><Pagination page={Math.min(page,pages)} pages={pages} pathname="/products" params={{q:query.q,category:query.category}}/></main>;
}
