import Link from "next/link";
import { notFound } from "next/navigation";
import { DataTable, PageHeader, StatusIndicator } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatDate, formatMoney } from "@/lib/pricing";
import { normalizeOfferPrice } from "@/lib/pricing/normalization";

export default async function ListinoDetail({ params }: { params: Promise<{ id: string }> }) {
  await requireRoles(["PROCUREMENT_MANAGER", "PROCUREMENT_ADMIN"]);
  const list = await prisma.priceList.findUnique({ where: { id: (await params).id }, include: { supplier: true, sourceDocument: { include: { uploadedBy: true } }, publishedBy: true, previousVersion: true, importJob: true, offers: { include: { canonicalProduct: true } } } });
  if (!list) notFound();
  return <main><PageHeader eyebrow={list.supplier.name} title={list.name} description={`${formatDate(list.validFrom)} – ${formatDate(list.validUntil)} · versione ${list.version}`} action={<div className="cta-row"><Link className="secondary-cta" href="/imports/new">Importa nuova versione</Link>{list.importJob && <Link className="primary-cta" href={`/imports/${list.importJob.id}/changes`}>Analizza variazioni</Link>}</div>} /><section className="definition-grid"><div><span>Stato</span><StatusIndicator active={list.active} label={list.active ? "Attivo" : "Versione storica"} /></div><div><span>Articoli</span><strong>{list.offers.length}</strong></div><div><span>Versione</span><strong>v{list.version}</strong></div><div><span>Versione precedente</span><strong>{list.previousVersion ? <Link href={`/price-lists/${list.previousVersion.id}`}>v{list.previousVersion.version}</Link> : "Prima versione"}</strong></div></section>{list.sourceDocument && <section className="price-list-provenance"><div><p className="eyebrow">Provenienza verificabile</p><h2>{list.sourceDocument.originalFilename}</h2><p>Caricato da {list.sourceDocument.uploadedBy.name} il {formatDate(list.sourceDocument.uploadedAt)} · pubblicato da {list.publishedBy?.name ?? "—"} il {formatDate(list.publishedAt)}.</p></div><div className="cta-row"><Link className="secondary-cta" href={`/imports/documents/${list.sourceDocument.id}`}>Apri originale</Link>{list.importJob && <Link className="secondary-cta" href={`/imports/${list.importJob.id}`}>Apri revisione</Link>}</div></section>}<DataTable label="Articoli del listino"><thead><tr><th>Prodotto</th><th>Codice fornitore</th><th>Confezione</th><th>Prezzo</th><th>Prezzo normalizzato</th><th>Convenzionato</th></tr></thead><tbody>{list.offers.map((offer) => { const normalized = normalizeOfferPrice(offer.canonicalProduct, offer); return <tr key={offer.id}><td><Link className="table-link" href={`/products/${offer.canonicalProductId}`}>{offer.canonicalProduct.name}</Link></td><td className="mono">{offer.supplierSku ?? "—"}</td><td>{offer.canonicalProduct.packageDescription}</td><td>{formatMoney(Number(offer.unitPrice))}</td><td>{normalized.normalizedLabel}</td><td>{offer.preferred ? "Sì" : "No"}</td></tr>; })}</tbody></DataTable></main>;
}
