import Link from "next/link";
import { ChevronIcon } from "@/components/icons";
import { EmptyState, PageHeader, SearchField } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { formatMoney, getComparablePrice, getPreferredOffer } from "@/lib/pricing";
import { prisma } from "@/lib/prisma";

type Props = { searchParams: Promise<{ q?: string; category?: string; preferred?: string; sort?: string }> };
export default async function CatalogPage({ searchParams }: Props) {
  await requireRoles(["RSA_DIRECTOR", "AREA_MANAGER"]); const filters = await searchParams;
  const [categories, products] = await Promise.all([prisma.category.findMany({ orderBy: { name: "asc" } }), prisma.canonicalProduct.findMany({ where: { AND: [filters.q ? { OR: [{ name: { contains: filters.q, mode: "insensitive" } }, { brand: { contains: filters.q, mode: "insensitive" } }] } : {}, filters.category ? { categoryId: filters.category } : {}, filters.preferred === "true" ? { offers: { some: { preferred: true } } } : {}] }, include: { category: true, offers: { include: { supplier: true } } }, orderBy: filters.sort === "name-desc" ? { name: "desc" } : { name: "asc" } })]);
  return <main><PageHeader eyebrow="Purchasable catalog" title="Catalog" description="Canonical products with current supplier coverage and preferred pricing." /><form className="filter-bar"><SearchField defaultValue={filters.q} placeholder="Search product or brand" /><select name="category" defaultValue={filters.category ?? ""}><option value="">All categories</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><label className="checkbox"><input type="checkbox" name="preferred" value="true" defaultChecked={filters.preferred === "true"} /> Preferred only</label><select name="sort" defaultValue={filters.sort ?? "name-asc"}><option value="name-asc">Name A–Z</option><option value="name-desc">Name Z–A</option></select><button>Apply</button></form>{products.length ? <div className="catalog-list">{products.map((product) => { const preferred = getPreferredOffer(product.offers); return <Link href={`/products/${product.id}`} className="catalog-row" key={product.id}><div className="product-monogram">{product.name.slice(0, 2).toUpperCase()}</div><div className="catalog-main"><span>{product.category.name}</span><h2>{product.name}</h2><p>{product.brand ?? "Unbranded"} · {product.uom}</p></div><div className="catalog-price"><span>Preferred price</span><strong>{preferred ? formatMoney(getComparablePrice(preferred), 4) : "—"}</strong><small>{preferred?.supplier.name ?? "No preferred offer"}</small></div><div className="offer-count"><strong>{product.offers.length}</strong><span>{product.offers.length === 1 ? "offer" : "offers"}</span></div><ChevronIcon /></Link>; })}</div> : <EmptyState title="No products match" description="Adjust search or filters to return to the available catalog." />}</main>;
}
