import Link from "next/link";
import { Metric, PageHeader } from "@/components/ui";
import { requireRoles } from "@/lib/auth";
import { compareOffers, formatMoney } from "@/lib/pricing";
import { prisma } from "@/lib/prisma";

export default async function ControlTowerPage() {
  await requireRoles(["EXECUTIVE_SPONSOR"]); const [organizations, facilities, suppliers, productCount, priceLists, offerCount, products] = await Promise.all([prisma.organization.count(), prisma.facility.count(), prisma.supplier.count({ where: { active: true } }), prisma.canonicalProduct.count(), prisma.priceList.count({ where: { active: true } }), prisma.supplierOffer.count(), prisma.canonicalProduct.findMany({ include: { category: true, offers: { include: { supplier: true } } } })]); const opportunities = products.filter((p) => p.offers.length > 1).map((product) => ({ product, result: compareOffers(product.offers) })).filter((item) => item.result.spread > 0).sort((a, b) => b.result.spread - a.result.spread);
  return <main><PageHeader eyebrow="Executive overview" title="Control Tower" description="Current network scale and observable price variation. No projected annual savings are assumed." /><div className="metrics-grid executive"><Metric label="Organizations" value={organizations} /><Metric label="Facilities" value={facilities} /><Metric label="Active suppliers" value={suppliers} /><Metric label="Canonical products" value={productCount} /><Metric label="Active price lists" value={priceLists} /><Metric label="Supplier offers" value={offerCount} /><Metric label="Comparable products" value={opportunities.length} /></div><section className="section-heading"><div><p className="eyebrow">Observed market signal</p><h2>Price harmonization opportunities</h2></div><span>Current normalized prices</span></section><div className="opportunity-list">{opportunities.map(({ product, result }, index) => <article key={product.id}><span className="rank">{String(index + 1).padStart(2, "0")}</span><div><small>{product.category.name}</small><Link href={`/products/${product.id}`}>{product.name}</Link></div><div><span>Observed price spread</span><strong>{result.spread.toFixed(1)}%</strong><small>{formatMoney(result.deltaEuro, 4)} per normalized unit</small></div></article>)}</div></main>;
}
